#!/bin/bash
# Скрипт установки Dante SOCKS прокси
# Использует те же команды что и Postal

set -e  # Остановиться при ошибке
set -x  # Показывать каждую команду

echo "=== Начало установки Dante SOCKS прокси ==="
echo "Время: $(date)"

# Step 1: Проверка ОС
echo ""
echo "=== Шаг 1: Проверка операционной системы ==="
cat /etc/os-release | grep -E '(^ID=|^VERSION_ID=)'

# Step 2: Обновление списка пакетов
echo ""
echo "=== Шаг 2: Обновление списка пакетов ==="
apt-get update -qq || yum update -y -q

# Step 3: Установка Dante
echo ""
echo "=== Шаг 3: Установка Dante SOCKS server ==="
echo "Это может занять 2-3 минуты..."
DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confnew" dante-server || yum install -y dante-server

# Step 4: Создание конфигурации Dante
echo ""
echo "=== Шаг 4: Создание конфигурации Dante ==="

# Получение IP Postal сервера (или использование 0.0.0.0 для теста)
POSTAL_IP="${POSTAL_IP:-0.0.0.0}"
echo "POSTAL_IP = $POSTAL_IP"

cat > /etc/danted.conf << 'DANTE_EOF'
# Dante SOCKS server configuration
# Auto-generated by Postal IP Pool Manager

logoutput: syslog

# Internal interface (listen for connections)
internal: 0.0.0.0 port = 1080

# External interface (for outgoing connections)
external: eth0

# Authentication methods
clientmethod: none
socksmethod: none

# Client access rules (only from Postal server)
client pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    log: connect disconnect error
}

# SOCKS rules
socks pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    protocol: tcp
    command: connect
    log: connect disconnect error
}

# Block everything else
client block {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    log: connect error
}

socks block {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    log: connect error
}
DANTE_EOF

echo "Конфигурация создана в /etc/danted.conf"
echo "Содержимое:"
cat /etc/danted.conf

# Step 5: Включение и запуск Dante
echo ""
echo "=== Шаг 5: Запуск сервиса Dante ==="
systemctl enable danted || chkconfig danted on
systemctl restart danted || service danted restart

# Даем время на запуск
sleep 2

# Step 6: Проверка статуса
echo ""
echo "=== Шаг 6: Проверка статуса сервиса ==="
systemctl status danted || service danted status

# Проверка что порт 1080 открыт
echo ""
echo "=== Проверка что порт 1080 слушает ==="
netstat -tulpn | grep 1080 || ss -tulpn | grep 1080

echo ""
echo "=== Установка завершена успешно! ==="
echo "Dante SOCKS прокси запущен на порту 1080"
