X-Deliver-Recipient: dave@outlook.com
Received: from localhost.localdomain (my.viaduct.io [2a01:78e0:a:1::a006]) by deliver03.infra.atech.io with SMTP; Thu, 06 Oct 2016 13:24:03 +0100
Date: Thu, 06 Oct 2016 13:24:03 +0100
From: The Viaduct Team <team@viaduct.io>
To: dave@outlook.com
Message-ID: <57f64263ac25a_1c817db0cc629df@orchestra.mail>
Subject: Welcome to Viaduct
Mime-Version: 1.0
Content-Type: multipart/alternative;
 boundary="--==_mimepart_57f64263a0101_1c817db0cc6285";
 charset=UTF-8
Content-Transfer-Encoding: 7bit


----==_mimepart_57f64263a0101_1c817db0cc6285
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Hi Adam Cooke

We're delighted you=E2=80=99ve decided to sign up with Viaduct. To get st=
arted, we just need to confirm that you have access to this e-mail addres=
s. To confirm, just click the button below and we=E2=80=99ll validate you=
r account straight away and you can start using it.

https://my.viaduct.io/verify/50e2122d-df8c-4454-af8a-ebc808dcf29d

We=E2=80=99re always here if you need help, if you=E2=80=99ve got any que=
stions, please don=E2=80=99t hesitate to drop us an email (team@viaduct.i=
o) and we=E2=80=99ll be happy to help. You should also take a look at our=
 blog (https://blog.viaduct.io) for all our latest news & information.

All the best;

The Viaduct Team

----==_mimepart_57f64263a0101_1c817db0cc6285
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://ww=
w.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns=3D"http://www.w3.org/1999/xhtml" xmlns=3D"http://www.w3.org/1=
999/xhtml">
<head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Dutf-8" =
/>
<meta name=3D"viewport" content=3D"width=3Ddevice-width, initial-scale=3D=
1.0" />
<meta name=3D"format-detection" content=3D"telephone=3Dno" />
<meta http-equiv=3D"X-UA-Compatible" content=3D"IE=3Dedge" />
<title>Viaduct E-Mails</title>

</head>
<body marginwidth=3D"0" marginheight=3D"0" style=3D"-ms-text-size-adjust:=
 100% !important; -webkit-font-smoothing: antialiased !important; -webkit=
-text-size-adjust: 100% !important; margin: 0; padding: 0; width: 100% !i=
mportant;" offset=3D"0" topmargin=3D"0" leftmargin=3D"0" bgcolor=3D"#ffff=
ff"><style type=3D"text/css">
body {
margin: 0 !important; padding: 0 !important; width: 100% !important; -web=
kit-text-size-adjust: 100% !important; -ms-text-size-adjust: 100% !import=
ant; -webkit-font-smoothing: antialiased !important;
}
img {
border: 0 !important; outline: none !important; display: block !important=
;
}
@media only screen and (min-width:481px) and (max-width:599px) {
  table[class=3Dmain_table] {
    width: 480px !important;
  }
  table[class=3Dwrapper] {
    width: 100% !important;
  }
  td[class=3Dtxt_cnt] {
    text-align: center !important; padding-left: 10px !important; padding=
-right: 10px !important;
  }
  img[class=3Dimg_full] {
    width: 100% !important; height: auto !important;
  }
  td[class=3Dhide] {
    display: none !important;
  }
  br[class=3Dhide] {
    display: none !important;
  }
  td[class=3Dhight] {
    height: 40px !important;
  }
  td[class=3Dwelcome] {
    font-family: 'Helvetica Neue', Helvetica, Arial,sans-serif !important=
; font-size: 24px !important; line-height: 28px !important;
  }
  td[class=3Dpadding] {
    padding-left: 10px !important; padding-right: 10px !important;
  }
  img[class=3Dpadding] {
    padding-bottom: 25px !important;
  }
  td[class=3Dpadding_2] {
    padding-left: 25px !important; padding-right: 25px !important; text-a=
lign: center !important;
  }
}
@media only screen and (max-width:480px) {
  table[class=3Dmain_table] {
    width: 100% !important;
  }
  table[class=3Dwrapper] {
    width: 100% !important;
  }
  td[class=3Dtxt_cnt] {
    text-align: center !important; padding-left: 10px !important; padding=
-right: 10px !important;
  }
  img[class=3Dimg_full] {
    width: 100% !important; height: auto !important;
  }
  td[class=3Dhide] {
    display: none !important;
  }
  br[class=3Dhide] {
    display: none !important;
  }
  td[class=3Dhight] {
    height: 40px !important;
  }
  td[class=3Dwelcome] {
    font-family: 'Helvetica Neue', Helvetica, Arial,sans-serif !important=
; font-size: 24px !important; line-height: 28px !important;
  }
  td[class=3Dpadding] {
    padding-left: 10px !important; padding-right: 10px !important;
  }
  img[class=3Dpadding] {
    padding-bottom: 25px !important;
  }
  td[class=3Dpadding_2] {
    padding-left: 25px !important; padding-right: 25px !important; text-a=
lign: center !important;
  }
  img[class=3Dlogo] {
    width: 21px !important; height: 21px !important;
  }
}
</style>
<table width=3D"100%" border=3D"0" cellspacing=3D"0" cellpadding=3D"0" al=
ign=3D"center" style=3D"border-collapse: collapse !important; mso-table-l=
space: 0pt; mso-table-rspace: 0pt; padding: 0px;">
  <tr>
    <td align=3D"center" valign=3D"top" bgcolor=3D"#2b3034" style=3D"bord=
er-collapse: collapse; mso-line-height-rule: exactly;">
      <table width=3D"554" border=3D"0" cellspacing=3D"0" cellpadding=3D"=
0" align=3D"center" class=3D"main_table" style=3D"border-collapse: collap=
se !important; mso-table-lspace: 0pt; mso-table-rspace: 0pt; padding: 0px=
; table-layout: fixed;">
        <tr>
          <td class=3D"hide" height=3D"1" valign=3D"top" style=3D"border-=
collapse: collapse; font-size: 0px; line-height: 0px; mso-line-height-rul=
e: exactly;"><img src=3D"https://cdn.viaduct.io/emails/201502/spacer.gif"=
 height=3D"1" width=3D"554" style=3D"border: 0; display: block !important=
; max-height: 1px; min-height: 1px; min-width: 554px; outline: none !impo=
rtant; width: 554px;" border=3D"0" alt=3D"" /></td>
        </tr>
        <tr>
          <td class=3D"hight" height=3D"90" style=3D"border-collapse: col=
lapse; mso-line-height-rule: exactly;">=C2=A0</td>
        </tr>
        <tr>
          <td align=3D"center" valign=3D"top" style=3D"border-collapse: c=
ollapse; font-size: 0px; line-height: 0px; mso-line-height-rule: exactly;=
"><a href=3D"#" target=3D"_blank"><img class=3D"logo" src=3D"https://cdn.=
viaduct.io/emails/201502/logo@2x.png" width=3D"41" height=3D"41" alt=3D"V=
iaduct" style=3D"border: 0; display: block !important; max-width: 41px; o=
utline: none !important;" border=3D"0" /></a></td>
        </tr>
        <tr>
          <td class=3D"hight" height=3D"60" style=3D"border-collapse: col=
lapse; mso-line-height-rule: exactly;">=C2=A0</td>
        </tr>
        <tr>
          <td class=3D"welcome" align=3D"center" valign=3D"top" style=3D"=
border-collapse: collapse; color: #ffffff; font-family: 'Helvetica Neue',=
 Helvetica,Arial,sans-serif; font-size: 38px; font-weight: 300; line-heig=
ht: 38px; mso-line-height-rule: exactly;">
            Welcome to Viaduct
          </td>
        </tr>
        <tr>
          <td height=3D"50" style=3D"border-collapse: collapse; mso-line-=
height-rule: exactly;">=C2=A0</td>
        </tr>
        <tr>
          <td class=3D"padding" align=3D"center" valign=3D"top" style=3D"=
border-collapse: collapse; color: #ffffff; font-family: 'Helvetica Neue',=
 Helvetica, Arial,sans-serif; font-size: 16px; line-height: 27px; mso-lin=
e-height-rule: exactly;">
              <span style=3D"font-weight: bold;">Hi Dave</span>
              - We=E2=80=99re delighted you=E2=80=99ve decided to sign up=
 with Viaduct. To get started, we just need to
              confirm that you have access to this e-mail address. To con=
firm, just click the button below and we=E2=80=99ll
              validate your account straight away and you can start using=
 it.
            </td>
        </tr>
        <tr>
          <td class=3D"hight" height=3D"50" style=3D"border-collapse: col=
lapse; mso-line-height-rule: exactly;">=C2=A0</td>
        </tr>
        <tr>
          <td align=3D"center" valign=3D"top" style=3D"border-collapse: c=
ollapse; mso-line-height-rule: exactly;">
            <table width=3D"216" border=3D"0" cellspacing=3D"0" cellpaddi=
ng=3D"0" align=3D"center" bgcolor=3D"#c1d54a" style=3D"border-collapse: c=
ollapse !important; mso-table-lspace: 0pt; mso-table-rspace: 0pt; padding=
: 0px;">
              <tr>
                <td class=3D"link" align=3D"center" valign=3D"middle" hei=
ght=3D"43" style=3D"border-collapse: collapse; color: #ffffff; font-famil=
y: 'Helvetica Neue', Helvetica, Arial,sans-serif; font-size: 16px; line-h=
eight: 18px; mso-line-height-rule: exactly;">
                  <a href=3D"https://my.viaduct.io/verify/50e2122d-df8c-4=
454-af8a-ebc808dcf29d" target=3D"_blank" style=3D"color: #ffffff; text-de=
coration: none;">
                    ACTIVATE MY ACCOUNT
                  </a>
                </td>
              </tr>
            </table>
          </td>
        </tr>
        <tr>
          <td class=3D"hight" height=3D"55" style=3D"border-collapse: col=
lapse; mso-line-height-rule: exactly;">=C2=A0</td>
        </tr>
        <tr>
          <td class=3D"padding" align=3D"center" valign=3D"top" style=3D"=
border-collapse: collapse; color: #ffffff; font-family: 'Helvetica Neue',=
 Helvetica, Arial,sans-serif; font-size: 16px; line-height: 27px; mso-lin=
e-height-rule: exactly;">
            We=E2=80=99re always here if you need help, if you=E2=80=99ve=
 got any questions, please don=E2=80=99t hesitate to
            <a class=3D"link2" href=3D"mailto:team@viaduct.io" target=3D"=
_blank" style=3D"color: #c1d54a; text-decoration: underline;">drop us an =
email</a>
            and we=E2=80=99ll be happy to help. You should also take a lo=
ok at
            <a class=3D"link2" href=3D"https://blog.viaduct.io" target=3D=
"_blank" style=3D"color: #c1d54a; text-decoration: underline;">our blog</=
a> for
            all our latest news &amp; information.</td>
        </tr>
        <tr>
          <td class=3D"hight" height=3D"75" style=3D"border-collapse: col=
lapse; mso-line-height-rule: exactly;">=C2=A0</td>
        </tr>
        <tr>
          <td align=3D"center" valign=3D"top" style=3D"border-collapse: c=
ollapse; mso-line-height-rule: exactly;">
            <img src=3D"https://cdn.viaduct.io/emails/201502/the_viaduct_=
team.png" width=3D"177" height=3D"31" alt=3D"The viaduct team" style=3D"b=
order: 0; display: block !important; outline: none !important;" border=3D=
"0" />
          </td>
        </tr>
        <tr>
          <td class=3D"hight" height=3D"80" style=3D"border-collapse: col=
lapse; mso-line-height-rule: exactly;">=C2=A0</td>
        </tr>
        <tr>
          <td align=3D"center" valign=3D"top" style=3D"border-collapse: c=
ollapse; mso-line-height-rule: exactly;">
            <img class=3D"img_full" src=3D"https://cdn.viaduct.io/emails/=
201502/banner@2x.png" width=3D"554" alt=3D"Banner" style=3D"border: 0; di=
splay: block !important; max-width: 554; outline: none !important;" borde=
r=3D"0" />
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td align=3D"center" valign=3D"top" bgcolor=3D"#c1d54a" style=3D"bord=
er-collapse: collapse; mso-line-height-rule: exactly;">
      <table width=3D"554" border=3D"0" cellspacing=3D"0" cellpadding=3D"=
0" align=3D"center" class=3D"main_table" style=3D"border-collapse: collap=
se !important; mso-table-lspace: 0pt; mso-table-rspace: 0pt; padding: 0px=
; table-layout: fixed;">
        <tr>
          <td width=3D"27" class=3D"hide" style=3D"border-collapse: colla=
pse; mso-line-height-rule: exactly;"></td>
          <td align=3D"left" valign=3D"top" style=3D"border-collapse: col=
lapse; mso-line-height-rule: exactly;">
            <table width=3D"500" border=3D"0" cellspacing=3D"0" cellpaddi=
ng=3D"0" align=3D"center" class=3D"wrapper" style=3D"border-collapse: col=
lapse !important; mso-table-lspace: 0pt; mso-table-rspace: 0pt; padding: =
0px;">
              <tr>
                <td class=3D"hight" height=3D"58" style=3D"border-collaps=
e: collapse; mso-line-height-rule: exactly;">=C2=A0</td>
              </tr>
              <tr>
                <td align=3D"center" valign=3D"top" style=3D"border-colla=
pse: collapse; mso-line-height-rule: exactly;">
                  <table width=3D"128" border=3D"0" cellspacing=3D"0" cel=
lpadding=3D"0" align=3D"right" class=3D"wrapper" style=3D"border-collapse=
: collapse !important; mso-table-lspace: 0pt; mso-table-rspace: 0pt; padd=
ing: 0px;">
                    <tr>
                      <td align=3D"center" valign=3D"top" style=3D"border=
-collapse: collapse; mso-line-height-rule: exactly;">
                        <a href=3D"http://viaduct.io" target=3D"_blank">
                          <img class=3D"padding" src=3D"https://cdn.viadu=
ct.io/emails/201502/Vector@2x.png" width=3D"128" height=3D"29" alt=3D"Via=
duct" style=3D"border: 0; display: block !important; max-width: 128px; ou=
tline: none !important;" border=3D"0" /></a>
                      </td>
                    </tr>
                  </table>
                  <table width=3D"285" border=3D"0" cellspacing=3D"0" cel=
lpadding=3D"0" align=3D"left" class=3D"wrapper" style=3D"border-collapse:=
 collapse !important; mso-table-lspace: 0pt; mso-table-rspace: 0pt; paddi=
ng: 0px;">
                    <tr>
                      <td class=3D"txt_cnt" align=3D"left" valign=3D"top"=
 style=3D"border-collapse: collapse; color: #ffffff; font-family: 'Helvet=
ica Neue', Helvetica, Arial, sans-serif; font-size: 13px; line-height: 18=
px; mso-line-height-rule: exactly;">Viaduct is an hosting platform for de=
velopers. Designed with flexibility, speed &amp; affordabiity in mind at =
every step of the process.</td>
                    </tr>
                  </table>
                </td>
              </tr>
              <tr>
                <td height=3D"35" style=3D"border-collapse: collapse; mso=
-line-height-rule: exactly;">=C2=A0</td>
              </tr>
              <tr>
                <td class=3D"padding_2" align=3D"left" valign=3D"top" sty=
le=3D"border-collapse: collapse; color: #768425; font-family: 'Helvetica =
Neue', Helvetica, Arial,sans-serif; font-size: 13px; line-height: 18px; m=
so-line-height-rule: exactly;">
                </td>
              </tr>
              <tr>
                <td height=3D"90" class=3D"hight" style=3D"border-collaps=
e: collapse; mso-line-height-rule: exactly;"></td>
              </tr>
            </table>
          </td>
          <td width=3D"27" class=3D"hide" style=3D"border-collapse: colla=
pse; mso-line-height-rule: exactly;"></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<div style=3D"color: #ffffff; display: none; font: 15px courier; white-sp=
ace: nowrap;"> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - =
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - </div>
</body>
</html>

----==_mimepart_57f64263a0101_1c817db0cc6285--
