Received: from localhost.localdomain (2a01:78e0:a:1:1:0:a:a6 [2a01:78e0:a:1:1:0:a:a6]) by deliver03.infra.atech.io with SMTP; Tue, 04 Oct 2016 14:02:20 +0100
Date: Tue, 04 Oct 2016 13:02:19 +0000
From: VoIP Front <sales@voipfront.co.uk>
To: adam@dial9.co.uk
Message-ID: <57f3a85b35545_c3fb4723b62c4897f4@vdtapp-380-39472-0d3343561f.mail>
Subject: Order Received
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

Hello Team!

Re: Order #000830

We're pleased to let you know that we have just received a new order! You might want to accept and ship it.

Many thanks,

VoIP Front
sales@voipfront.co.uk
