X-Deliver-Recipient: hello@atechmedia.com
X-Spam-Checker-Version: SpamAssassin 3.4.0 (2014-02-07) on
	deliver03.infra.atech.io
X-Spam-Level: 
X-Spam-Status: No, score=-0.2 required=5.0 tests=BAYES_00,
	HTML_FONT_LOW_CONTRAST,HTML_MESSAGE,MIME_HTML_MOSTLY,MPART_ALT_DIFF,
	RCVD_IN_DNSWL_NONE,SPF_HELO_PASS,T_DKIM_INVALID,URIBL_GREY autolearn=no
	autolearn_force=no version=3.4.0
Received: from EUR01-HE1-obe.outbound.protection.outlook.com (mail-he1eur01lp0203.outbound.protection.outlook.com [2a01:111:f400:7e1f::203]) by deliver03.infra.atech.io with SMTP; Mon, 17 Oct 2016 10:28:24 +0100
Received: from DB3PR05CA0075.eurprd05.prod.outlook.com (10.163.44.43) by
 AMXPR05MB215.eurprd05.prod.outlook.com (10.242.73.21) with Microsoft SMTP
 Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P384) id
 15.1.669.12; Mon, 17 Oct 2016 09:28:21 +0000
Received: from AM5EUR02FT034.eop-EUR02.prod.protection.outlook.com
 (2a01:111:f400:7e1e::204) by DB3PR05CA0075.outlook.office365.com
 (2a01:111:e400:9448::43) with Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P384) id 15.1.669.12 via
 Frontend Transport; Mon, 17 Oct 2016 09:28:21 +0000
Authentication-Results: spf=pass (sender IP is 199.16.156.179)
 smtp.mailfrom=bounce.twitter.com; atechmedia.com; dkim=pass (signature was
 verified) header.d=twitter.com;atechmedia.com; dmarc=pass action=none
 header.from=twitter.com;atechmedia.com; dkim=pass (signature was verified)
 header.d=twitter.com;
Received-SPF: Pass (protection.outlook.com: domain of bounce.twitter.com
 designates 199.16.156.179 as permitted sender)
 receiver=protection.outlook.com; client-ip=199.16.156.179;
 helo=spring-chicken-bn.twitter.com;
Received: from spring-chicken-bn.twitter.com (199.16.156.179) by
 AM5EUR02FT034.mail.protection.outlook.com (10.152.8.118) with Microsoft SMTP
 Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256_P256) id
 15.1.669.7 via Frontend Transport; Mon, 17 Oct 2016 09:28:20 +0000
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=twitter.com;
	s=dkim-201406; t=1476695299;
	bh=LgMXW+6VfLHasuTQI/R3SrR3H+H99YtipORTEX8Simc=;
	h=Date:From:To:Subject:MIME-Version:Content-Type:List-Unsubscribe:
	 Message-ID;
	b=SkpxPBxIVtpBCATHYbj7JI14zep0eFLgrUO+cXKqArq4pOoOduKvE/YC0in5LGiaf
	 IcQke5g3JQ2DC6qLgsTVC/cNsyVWSWSWOvCVbE6Lh9bcgGfaumbftURBA5qI8Lztum
	 7pROJ6kkPh0hwqaY9jFFIcWlCGMmxlcHnK9DsdbTxlSYmUN0U502/TqmG/HMpNID9b
	 /OJNz6XDKApCB0DJQcAcfky41m2bhKz7rJ+YpgpeKorzI5CK2J7zcwlhSCm4fdaiHS
	 Xt2sPCCHdtcWcfmfReBQJe6V7Jizas3vNmT37PUiXKkEaukNlnnr2S0zjoC6Q7CQOb
	 kgphYybci1pkA==
X-MSFBL: WNBhBihNKIxVp0wVvT5mStfM+hqq7GmoRWgPxruw4uM=|eyJnIjoiRXZlcnl0aGl
	uZyIsInUiOiJoZWxsb0BhdGVjaG1lZGlhLmNvbUBpaWQjI2Y1MmI1ZjRhNDg3NDQ
	zNzI4NDQ5YzdiOTgxNDg5MDk2QHVzYiMjMzBAMjQ0QDI4MTA0NjE1QDBAMjYxZTd
	iMzM1OWFiODM1ZDI2NTQwN2FhZDgxZmNkNjM2MTYwYWJkOCIsInIiOiJoZWxsb0B
	hdGVjaG1lZGlhLmNvbSIsImIiOiJhdGxhLWFxbS0zNy1zcjEtRXZlcnl0aGluZy4
	xOTkifQ==
Date: Mon, 17 Oct 2016 09:08:19 +0000
From: Twitter for Business <info@twitter.com>
To: aTech Media <hello@atechmedia.com>
Subject: @atechmedia, effectively reach new customers
MIME-Version: 1.0
Content-Type: multipart/alternative; 
	boundary="----=_Part_20209459_199831831.1476695299532"
List-Unsubscribe: <https://twitter.com/i/u?t=1&listunsub=t&cn=c21ic3NfYWNxX2NoYWluXzEx&sig=f16c28eefb612813b2dccc519147426d1dc14e8f&iid=f52b5f4a487443728449c7b981489096&uid=28104615&nid=244+26&usbid=30>
Feedback-ID: 0040162518f58f41d1f0:0048183034d98b50d6cafd24be6f7a9ea58b:GB:twitterESP
Precedence: Bulk
Message-ID: <66.95.56164.30594085@twitter.com>
Return-Path: b0091219fb3hello=atechmedia.com@bounce.twitter.com
X-EOPAttributedMessage: 0
X-EOPTenantAttributedMessage: 7a8f6edf-720f-4e3d-b767-1360e39a8cdf:0
X-Forefront-Antispam-Report:
	CIP:199.16.156.179;IPV:NLI;CTRY:US;EFV:NLI;SFV:NSPM;SFS:(8156002)(31570200002)(3000300001)(438002)(286005)(189002)(199003)(19617315012)(236004)(19627405001)(84326002)(626004)(18206015028)(4001070100004)(8676002)(110136003)(107886002)(118246002)(103116003)(5000100001)(36756003)(11100500001)(18926405002)(110436001)(956001)(270700001)(1096003)(77096005)(586003)(146002)(8896002)(106466001)(7596002)(15975445007)(450100001)(85226003)(64016003)(4290100001)(25786007)(53416004)(7846002)(356003)(620700001)(229853001)(47976999)(19580395003)(7636002)(246002)(18926415007)(7906003)(92566002)(54356999)(6916009)(50986999);DIR:INB;SFP:;SCL:1;SRVR:AMXPR05MB215;H:spring-chicken-bn.twitter.com;FPR:;SPF:Pass;PTR:spring-chicken-bn.twitter.com;MX:1;A:0;LANG:en;
X-Microsoft-Exchange-Diagnostics: 1;AM5EUR02FT034;1:vIWMQWgrUBX0kRrJUvGndC3iLng6ZOHw4frJSOHCirNutKWW1q9HWAwiPeHIUSfC7hHrBZs9j5aQ41YuGepDe42pxAkzyzb7Gzi8cJ4TdAPQXgs+xZIvVcpiZHvliiYg0d/41TzkFQZaHBUxVdVGdVsv4M+bpCvMK0H3zrYLtKHc9oPk5wNxPrDTDj1kdhASTAC8inA6/nGntDZu1xEkpNOzpBEhsIyZ2Ld24h48kxFaQ9P6Es4bKGBIkugy5Tm4prEV0NPdCcPuCVrix7cEL381H7PiJw5scClHRszRuyQ9On9uJnI2/hxoz1ooGKbhcuCzQq67XzmSR20pHWw+lmDwF/9JmKYHAx3V2/BS63nAQnzTJ8s5raxqcqYuTWeT5HsrBKWsWQWFHgAVQFTYTfgWCkzN4o4nqqdXl8bKk8ORXuGkorbDSVhzZxXwlsxA8zQ4jg7XDEpgb6eJpzfq4iHvlqw4W4fmZZ1BCnaANwdPRnazJFU6Jo0MEqUPaii65QJ69EsKxXN+0BT6/n0LIXlZsh4Svp4bqB1LoY2+tCu951d2OKDxqBmkUfhKXG7xCvtvPZtQlDxEZYqMcwvhiA==
X-MS-Office365-Filtering-Correlation-Id: 3039e27b-7d16-461b-3a3d-08d3f66fefbf
X-Microsoft-Exchange-Diagnostics:
	1;AMXPR05MB215;2:xFSkW47+CfYGfvdjEVVGJ5XvaAu1J/ABXIf+0TMZieWuTjQRMI27ecqYElcYtoNANDOMjB+8zu+soKcEo5KYpf7+UzpexZzO6L7FHBAAwtzP6CjMlYKM4uT/+n2jDt5J0ODHUHt0aUdhADrAt+BpW7gD5m4qoYfkcQg5sh3ZK4G41IfmKBf63acJ/3NZrNnVYMu3U1Ha6Y+JdkgtcFDfzw==;3:nZag2xv1dvQVwmc7i3GGHtRkh2jgJLjrMNmWOgDmhdCtYXS0fTma0qD34uiOg5FB3IxXrKWdrd2pwmdVluWoZdvtI3dMVsj+QDKKiEn401jEJ9dLnFXTJcz64ImJ0T1XNp8HoN6oCYgy6NinlQVV4aZEiYqSCHpGP80i/S4v1dmUeBUA3JuPCzR6vY6Yz7F1l4/FhdRn88Up+vWTuY2FKPnkQQHDJcVHA4/PDFVcBSE4KZp1uMWxpXuOFNrASA7ZFWXFJwujovOS7blz+EC63frZlCM0nF0jJyk8PdMcPklaTbfJpaAHF+ZiOg7mMpWupBAiiMWrnXfXb/3kxJzMR3egz9lrvE8Xf3mZpTS5NlBUjk8HWh3Q3+wuniZRScDy1TA1+R5VXR4R65h8j3HLjA==
X-DkimResult-Test: Passed
X-Microsoft-Antispam:
	UriScan:;BCL:1;PCL:0;RULEID:(421252002)(8251501002)(3001016)(3010002)(71701004)(71702002);SRVR:AMXPR05MB215;
X-Microsoft-Exchange-Diagnostics:
	=?us-ascii?Q?1;AMXPR05MB215;25:GgSf1uB5xPLw7WKc2jplH7jDAsSN6Zm6DKkev+oOpF?=
 =?us-ascii?Q?eflgy3ApQOPL99aikD+EEpSM0VxFZbf2hNBCDgdCbZnd40msn95Ya5zhXHN4?=
 =?us-ascii?Q?SFRJXu5q30ShCVSZwccfrUhLKRC04jO0MNNBghaNwxIKnkfu4uY9AVteayfP?=
 =?us-ascii?Q?4vWGzrUAae1MTcEp+atJt8KWfEHXOM3+4/Lh87gAXFpISAX9PsnTYr0xAl6P?=
 =?us-ascii?Q?vstzyTEm8h/Vcl7Awl8+kAKfX5pcdJMZUUiMt5/qPghCnHpLuD3Hscx+ovXE?=
 =?us-ascii?Q?Tr+DUkVGqGhAjEmkVFfOeo35qJ9nvsiLDor7bY7RIdvVdAFiUGfTKikHDGYl?=
 =?us-ascii?Q?NXfPThzKtv0+cNIwyHFMLaXr31bHZbWw4IoE4o9fm1L/Q4quX0kvsQpCFHjT?=
 =?us-ascii?Q?HRbrwDr7Zm0aiEZ68xteishI8zMOtcpgn3OBExXhttMXawCi/g/+fuJUho62?=
 =?us-ascii?Q?i8t03FvLphOyF9I2DNk1ql32SI6/kC1u/bes3hLL9pQsvccbOOpI7aVmiqFx?=
 =?us-ascii?Q?c7Bi1+u5U5cpJUcD8OFOoUBc0XyAeCRsgQp9tRd4toHSiW0Rl7VZC9SCFugR?=
 =?us-ascii?Q?sBq2OlQA38iTW5bp7GhAdh85PSEX43rZITQzMUXY6DE4GrtuwHZDD8s/xT/8?=
 =?us-ascii?Q?cL4Vi/tKLk6Yq4BE+tmHvM1DNWfwm6RjpgdqDnEDHOcDderhxwGuh8d0uyBN?=
 =?us-ascii?Q?IffOH3Y7EVfr+I7vH3ejLHJuWsmho7uCckxq70CHCLgX+8k1gZd7TWWtZqBf?=
 =?us-ascii?Q?16dyB+IYGmBQKEtcB0zEjMEg1ZV4RHR8NkKXOYsq0vAqzR+gt+tn+0s6fx/0?=
 =?us-ascii?Q?0/ZWf0x0f7bNf01CroV1ZDSiGUWQluM1sEQUTmeLHJXES+ceO5T2Ig8jeddM?=
 =?us-ascii?Q?4Q5Yn3oEDBzYpQiChY3BZdBSg14vhe9J1WqDqXWoFAiep3Z/kd1fXcYKnD+O?=
 =?us-ascii?Q?3s8Pf8GasTf3gl+jXybvIKzgQSMSpQdMAkNJrenUgAt8HZOVVFVSSvpFgWEk?=
 =?us-ascii?Q?osAvmojeoFkRUol4U2ZdtWWt/gPO1iIifUFWj3hHyHAASHmsJ35qeQurbRcJ?=
 =?us-ascii?Q?p9xrs=3D?=
X-LD-Processed: 7a8f6edf-720f-4e3d-b767-1360e39a8cdf,ExtAddr
X-Microsoft-Exchange-Diagnostics:
	1;AMXPR05MB215;31:JzD3+6fXxaWDr4YxyrbPNPDM1HaX5DuokdBS4tjL2MeKKQGLZg0FmQNVjXVI8YEodgFAk3MakmO+TRTPtI9lECGowNexQVjT83EOKdAQ0by2mPF8rlWHrnDgPKV0xkUMV/AjDgVVfIjsny13RhlnV8Bafhxdvyr9T1iP1F/B0o0r1W/gyq0BxZqLNlKd1MdPoweZ6VNIG2IfDUTyduiEvr5oBPjD/PNWK+Nt2V/JGb/baWzsLapMJ32cni/kJ7kbGOjAHjRGYRy3kYQWU4wXtQ==;20:+9NkPI9t0YIJ4Xg+lIaNX8miDenKOU0NjrXZeQavI0z6h9oq16gXBFEX9Fd6nyR3P5AVFY2EsefMo3NfQBH2GarRVFCtZ6hz9+uUf3tANgSKYCiflhtRyexXD0Btpd/6LDngSMSBtWGrvq8bUhJnIENyFnpqBtLY/oRbGFtjHWc=
X-Exchange-Antispam-Report-Test:
	UriScan:(148322886591682)(31418570063057)(148717330147763)(171275909045310);
X-Exchange-Antispam-Report-CFA-Test:
	BCL:1;PCL:0;RULEID:(9101531078)(601004)(2401047)(701104)(8121501046)(13018025)(13016025)(9101536074)(3002001)(10201501046);SRVR:AMXPR05MB215;BCL:1;PCL:0;RULEID:;SRVR:AMXPR05MB215;
X-Microsoft-Exchange-Diagnostics:
	1;AMXPR05MB215;4:JwfG7N8rl6LK3NsPKzLZ4v5NcUQOOSr4V02ZxEnQMVN/z5NVec3aa3kBNMS7qzUsdPDNNx5JjxvLcb/6g2YnxyHF7ahJTNX/Nfw8sdSJPe0W5BQO/eBoofAwpNbnlj8NHDetNBixLale361QeLsNiURDdaPbE1mgXaR0X4Y0NsptC386j8R8/oRpcraYfO0e4UW5cCZA56DMipWWM8amyCd7dg5+mTqO5mp7opkgsGxxQ9CJ/c5OQKyIz70qETFwcgXRKLLcz5dI/pt2dbWx1TO5sJtx50ukPx1eKAKluSF/1nQO+qa34LPIhPP2SPi7giev12K79dDhTAeok5k0qpzTygaRiqeBwCf+WChcJDuUyuF1H39hkk+yqk26RWsWi+Bw/cG3NjS4Rsqyhj6Mkm6UO2zgSkDOcEm5HcMu9FvM6EtbCTOjisILBuan1QBgCGEqMvDKRg+XRNXQ1rx/ruQLdORkcy2q3KtBidKUjNVDqmdGBGDWEowMPLtwHoyBD6Rvj6d3UIkMKmsP+yemVSqVMcrdN1moUCK/ER0xGb4SHFlAuyso2bvA7xMO43Zx56SZAuwdnXlArg/39Ywp7JCoS6bTcpxwYZ+UpyXyMfy+bR8eC/e3DvmNQpKe6jnY
X-Microsoft-Exchange-Diagnostics:
	=?us-ascii?Q?1;AMXPR05MB215;23:bbFTdpG3OnFP9MDhkK6bDHuP2EDfQjuLNzpFjmC/eD?=
 =?us-ascii?Q?YfuoIlM4gdS2R1RhwxtwABOyKbKmjS54pw2EwjleNSoN96w6oSOwPTaQXGAg?=
 =?us-ascii?Q?8Tjfoamdzjg/oxnyAOpUWJk5/dulB+os1Ol09bZ1nm2pWqCPJyFNv2+GdrfJ?=
 =?us-ascii?Q?U1eIWJSLxPXK0jP61BwrWu2jATBkMryXj6GtBIl5J6y26Je1TA93OjUMsVGj?=
 =?us-ascii?Q?n7oEe3i+j0S5IS8O4tZfU37va9GqrCsa5yJz48acWRbjxV/Z9771/Ly7Zh9R?=
 =?us-ascii?Q?rSzrQcJMjy2k3y/j+qfuvLdOearAYvbYbdEVkjBXGXtY2cs2Hz7kbYV5wfUN?=
 =?us-ascii?Q?KuLxVA14d2N7+O8WwPoCaL96XDA9oyobJ7sxUvr6V/+e7ftV2yMuk3xV8kKX?=
 =?us-ascii?Q?8Np6xcLuzeaon4Kd4L2vS6cOVIyToCwrhfoXrRF06vS/TeA7Lr6tuLmx8FF6?=
 =?us-ascii?Q?IqYPx5kJP2yTqlP8AhP1Fk+xl69NQs76p0MAuYoELJIi0Mo4ILjJSWqIbGBA?=
 =?us-ascii?Q?gh20GOVGzb6khNByAmTEyWbPqfVHfyIBfBP+6o6XWShi2bxAxLx/XrJ4SeYL?=
 =?us-ascii?Q?hEbuixR4iZD9517wopflNHPiNTz5ToraXhoBxjT69EAjGqlhbpAP0M9gJeMp?=
 =?us-ascii?Q?rF8K0OToBrDE/RF67FtzEvcDGoZeGvGBhzb9njxNhR0ngkR3vPtz2vBsxkog?=
 =?us-ascii?Q?/41e5De4KB9TVWLUPIztv8LEkw4tj8WDm9ZpAStRjkJrA8NHfn7awJHhVvxj?=
 =?us-ascii?Q?O9lVmoN+v8qL7oo+KCkVkvmTFnAVDsjnWPVeUZwhYxv0PefMF72xH+vjJxFo?=
 =?us-ascii?Q?JV+EXNBUZU04rvSaaKTywsf9SOjlzxQL0ktAS7TsmGoY9sFq3x48n3sOVaWW?=
 =?us-ascii?Q?x0AY2tIZd1hCKC6mj4JfyQrXC9RuKC9BQ4UAi5kJVAySqwVWBFjau5dYFj+m?=
 =?us-ascii?Q?s23ldyJ4pKp7lQKR0jPxnls7q2cuuIbz9bq8j0CJJ9CbT1I4qjFV5jbULFof?=
 =?us-ascii?Q?R0DN3bxH5D6XnKBAIpu1qFp0Tv7jG0eizLi7g01mLzySrCLl/MyLe4gnIA/X?=
 =?us-ascii?Q?cHRiqF1YORpC78CfbAYPrQqd9vHfUJtwAcubKi6o/ZjbmdOMdD0osTAQEU9P?=
 =?us-ascii?Q?u5WofjLGWLNCZzWUAncPPC0n38nlAkADrK7IP7C/k7ALfY2vTdq2Cs9tjwJ5?=
 =?us-ascii?Q?gqXlspthXFVtaE6MGQlgRDEUN4HyQyOSIXYyJ/wf/55QC0JbgmSNjUTrQ++z?=
 =?us-ascii?Q?h7fUn/2lZeaV7dv+sSPJwL+vGnDDQszi63/IEM2yTgKztDZeQuD2iYoSd+1f?=
 =?us-ascii?Q?xbYnR+KKcdiHGjkZMxA6+JCMIYBmsRf4q65l4XoShi?=
X-Microsoft-Exchange-Diagnostics:
	1;AMXPR05MB215;6:9gGBK/Fc8f7KtChGuxHFpXJDEGL9ejaRnMXyvmLLY5bCWvVCkAv7K+VX6EQt8ekz2qDr6alb/NJqYm++5O8Ra+geg8Zfw35a1rhANCXZpUSqfNgPgHC21p+eVulMzXLTA7NJb/UT+qKBVv1enxG7lqSrCt4wm7FpEQpVf1gkof/S/wvI4EaXgVwjbgpc6ydPxB2gXLsgQ0Mtm7IfM7j5cdAh48GLPnQyunzI5jrhN6bC6Abhhp/cO4ngpnPcIGcwrQTwTXwtZ2NrE2rzJ+k7OkIPNm4lCM4hVQN8ppCO/ym+DCGRG06qDKnRf5dziOv8zzgcq1aG7C8lwRdkhWBevw==;5:0mIEsUiD4taNkLlaqddXDMQ3zkc2v9xLbgOHd4V/DRP5Cd1RrCS7nmBGEqdNnUaeksYN5Nizl0+kgyVTDTU4yNkKS9Rjc6sSXnxCpe7kWHRezi7Fh43YDhZi5zw4Fsq82+8bqzts9yDFDJ2n1WEFpNj43bwQD5yDreaaK3CVRs4=;24:yT6DyyZKAORzHh5LiEv9jC+mY/e/63do9DsREK9t4UF+XqWlrjimra+wO++LhByvS1jpOcAEvp1Y6YqD0KbsQ4t76oqsuECvnmDLF/g2uKg=
SpamDiagnosticOutput: 1:5
SpamDiagnosticMetadata: Default:1
X-Microsoft-Exchange-Diagnostics:
	1;AMXPR05MB215;7:oyVwILX3jt6hQw6WpNSGw5KQtiQnLMEXe+mixripKTSgv6TtiBxUnC8aoYF9+4OTx5iTLGupfxXEHGaDGVAhLRYFPyflqYueTsSQX/307fjWQpnLfkgX5t8SEijMb1AXHFS7REmJb3FSafjACI/1ZIgcif6JnPPYDDoO3oXGLmetUuD1tCg+rNh+OInD1mxUEDJ1gMzke4Kvr/S5fCIB/VqC7Tmf54UmBtPOzayMSZkqKcnXehdPBya9OoZywCCeYqkrRJNruoP5D8cP/E4U+ZVFokr0r136AUjA3P4Jru6KQKhs8/dgGtYgHjDX+duIWfxgAmOR1lMiT6qB7WPMHqTWfTf3Dp3AxEw94/gx56uZRBRAHr84FjLDI1diYGNg
X-OriginatorOrg: atech.media
X-MS-Exchange-CrossTenant-OriginalArrivalTime: 17 Oct 2016 09:28:20.5961
 (UTC)
X-MS-Exchange-CrossTenant-Id: 7a8f6edf-720f-4e3d-b767-1360e39a8cdf
X-MS-Exchange-CrossTenant-FromEntityHeader: Internet
X-MS-Exchange-Transport-CrossTenantHeadersStamped: AMXPR05MB215
X-MS-Exchange-CrossPremises-OriginalClientIPAddress: 199.16.156.179
X-MS-Exchange-CrossPremises-AuthSource:
	AM5EUR02FT034.eop-EUR02.prod.protection.outlook.com
X-MS-Exchange-CrossPremises-AuthAs: Anonymous
X-MS-Exchange-CrossPremises-AVStamp-Service: 1.0
X-MS-Exchange-CrossPremises-SCL: 1
X-MS-Exchange-CrossPremises-Antispam-ScanContext:
	DIR:Incoming;SFV:NSPM;SKIP:0;
X-MS-Exchange-CrossPremises-Processed-By-Journaling: Journal Agent
X-OrganizationHeadersPreserved: AMXPR05MB215.eurprd05.prod.outlook.com

------=_Part_20209459_199831831.1476695299532
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 7bit


------=_Part_20209459_199831831.1476695299532
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www=
.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Dutf-8" />
<meta name=3D"viewport" content=3D"width=3Ddevice-width, minimum-scale=3D1.=
0, maximum-scale=3D1.0, user-scalable=3D0" />
<meta name=3D"apple-mobile-web-app-capable" content=3D"yes" />
<style type=3D"text/css">

@media only screen and (max-width: 320px) {

td[class=3D"body-text"]{
padding-left: 5px !important;
padding-right: 5px !important;
font-size: 16px !important;
line-height: 22px !important;
font-weight: 400 !important;

}

td[class=3D"main-unit-height"]{
height: 30px !important;
}

td[class=3D"gutter"]{
width: 7px !important;
}

table[class=3D"body_wrapper"] {
width: 100% !important;
}

}


@media only screen and (max-width: 420px) {

img[class=3D"video-icon"]{
width: 40px;
}

td[class=3D"h1"]{
font-size:22px;
line-height: 30px;
}

td[class=3D"h1_header"]{
font-size:30px;
line-height: 40px;
}

td[class=3D"h2"]{
font-size:18px;
line-height: 25px;
}
td[class=3D"body-text"]{
font-size:16px;
line-height: 24px;
}
td[class=3D"sms-text"]{
font-size: 22px !important;
line-height: 32px !important;
padding-left: 5px !important;
padding-right: 5px !important;
}
td[class=3D"top-unit-height"]{
height: 30px !important;
}
td[class=3D"sms-top-height"]{
height: 40px !important;
}
td[class=3D"btm-unit-height"]{
height: 50px !important;
}
td[class=3D"sms-btm-height"]{
height: 50px !important;
}

table[class=3D"body_wrapper"] {
width: 100% !important;
}
}

@media only screen and (max-width: 600px) {

table[class=3D"collapse"]{
width:100% !important;
}

div[class=3D"collapse"]{
width:100% !important;
}

td[class=3D"logo_space"]{
height:12px !important;
}

span[class=3D"address"]{
display:block !important;
width:240px !important;
line-height:18px !important;
}

img[class=3D"media"]{
width: 100%;
}

table[class=3D"body_wrapper"] {
width: 100% !important;
}

table[class=3D"two-column"] {
width: 100% !important;
}
}


@media only screen and (max-width: 480px) {

table[class=3D"collapse"]{
width:100% !important;
}

div[class=3D"collapse"]{
width:100% !important;
}

td[class=3D"logo_space"]{
height:12px !important;
}

span[class=3D"address"]{
display:block !important;
width:240px !important;
line-height:18px !important;
}

td[class=3D"cut"]{
display:none !important;
}
td[class=3D"inline-space"]{
width:25px !important;
}
td[class=3D"hash-margin"]{
width: 5% !important;
}
td[class=3D"margins"]{
width:5% !important;
}
td[class=3D"paragraph-text"]{
text-align: center !important;

}
padding-bottom: 25px !important;{

}
td[class=3D"space"]{
height: 7px !important;
}
td[class=3D"space-420"]{
height: 17px !important;
}
td[class=3D"space-480"]{
height: 70px !important;
}
td[class=3D"cut-480"]{
display:none !important;
}
td[class=3D"btm-unit-height2"]{
height: 20px !important;
}

td[class=3D"btm-unit-height3"]{
height: 50px !important;
}

td[class=3D"stack-column"],
td[class=3D"stack-column-center"] {
display: block !important;
width: 100% !important;
}

td[class=3D"stack-column-center"] {
text-align: center !important;
}

td[class=3D"stack-column-center"] img {
padding-bottom: 10px;
}

table[class=3D"body_wrapper"] {
width: 100% !important;
}

table[class=3D"two-column"] {
padding-left: 0px !important;
padding-right: 0px !important;
margin-left: 0px !important;
width: 100% !important;
}

.two-column:last-child {
padding-bottom: 60px !important;
}

td[class=3D"paragraph-text"]{
text-align: center !important;
}

table[class=3D"wrap"] {
display: block !important;
width: 100% !important;
text-align: center !important;
margin: 0 auto;
padding-left: 0px !important;
padding-right: 0px !important;
margin-left: 0px !important;
}

td[class=3D"wrap"] {
display: block !important;
margin: auto !important;
width: 100% !important;
text-align: center !important;
}

img[class=3D"wrap"] {
display: block !important;
margin: auto !important;
width: 100% !important;
text-align: center !important;
padding-bottom: 30px !important
}

td[class=3D"h2"]{
text-align: center !important;
}

}


</style>
</head>
<body bgcolor=3D"#f5f8fa" style=3D"margin: 0;padding: 0;-webkit-text-size-a=
djust: 100%;-ms-text-size-adjust: 100%;margin:0;padding:0;-webkit-text-size=
-adjust:100%;-ms-text-size-adjust:100%;">
<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%" bgco=
lor=3D"#f5f8fa" style=3D"background-color: #f5f8fa;padding: 0;margin: 0;lin=
e-height: 1px;font-size: 1px;padding:0;margin:0;line-height:1px;font-size:1=
px;" class=3D"body_wrapper">
<tbody>
<tr>
<td align=3D"center" style=3D"padding: 0;margin: 0;line-height: 1px;font-si=
ze: 1px;padding:0;margin:0;line-height:1px;font-size:1px;">
<table class=3D"collapse" id=3D"header" align=3D"center" width=3D"680" styl=
e=3D"width: 680px;padding: 0;margin: 0;line-height: 1px;font-size: 1px;padd=
ing:0;margin:0;line-height:1px;font-size:1px;" bgcolor=3D"#ffffff" cellpadd=
ing=3D"0" cellspacing=3D"0" border=3D"0">
<tbody>
<tr>
<td style=3D"min-width: 680px;height: 1;padding: 0;margin: 0;line-height: 1=
px;font-size: 1px;padding:0;margin:0;line-height:1px;font-size:1px;" height=
=3D"1" class=3D"cut"> <img src=3D"https://ea.twimg.com/email/self_serve/med=
ia/spacer-1402696023930.png" height=3D"1" style=3D"min-width: 680px;height:=
 1px;margin: 0;padding: 0;display: block;-ms-interpolation-mode: bicubic;bo=
rder: none;outline: none;margin:0;padding:0;display:block;-ms-interpolation=
-mode:bicubic;border:none;outline:none;" /> </td>
</tr>
</tbody>
</table> </td>
</tr>
<tr>
<td align=3D"center" style=3D"padding: 0;margin: 0;line-height: 1px;font-si=
ze: 1px;padding:0;margin:0;line-height:1px;font-size:1px;">
<!--/////////////////// pre-header ///////////////////////////-->
<table class=3D"collapse" id=3D"hide" align=3D"center" width=3D"680" style=
=3D"width: 680px;padding: 0;margin: 0;line-height: 0;font-size: 0;display: =
none;max-height: 0;padding:0;margin:0;line-height:1px;font-size:1px;display=
:none;font-size:0;max-height:0;line-height:0;padding:0;" bgcolor=3D"#f5f8fa=
" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tbody>
<tr>
<td height=3D"25" style=3D"padding: 0;margin: 0;line-height: 1px;font-size:=
 1px;padding:0;margin:0;line-height:1px;font-size:1px;"></td>
</tr>
<tr align=3D"center">
<td class=3D"preheader" style=3D"padding: 0px;margin: 0px;line-height: 12px=
;font-size: 12px;font-family: 'Helvetica Neue Light', Helvetica, Arial, san=
s-serif;-webkit-font-smoothing: antialiased;color: #8899a6;font-weight: nor=
mal;padding:0;margin:0;line-height:1px;font-size:1px;font-family:'Helvetica=
 Neue Light', Helvetica, Arial, sans-serif;-webkit-font-smoothing:antialias=
ed;color:#8899a6;font-size:12px;padding:0px;margin:0px;font-weight:normal;l=
ine-height:12px;"> <a href=3D"https://twitter.com/i/redirect?url=3Dhttps%3A=
%2F%2Fanalytics.twitter.com%2Fuser%2F*%2Ftweets%3Ffilter%3Dtop%26utm_source=
%3Dlead_factory%26utm_medium%3Demail%26utm_content%3D11%26utm_campaign%3Dac=
q_chain&amp;t=3D1&amp;cn=3Dc21ic3NfYWNxX2NoYWluXzEx&amp;sig=3D431103191944a=
ab1b074cf0cf19df5b4772c2389&amp;iid=3Df52b5f4a487443728449c7b981489096&amp;=
uid=3D28104615&amp;nid=3D244+1553" style=3D"text-decoration: none;border-st=
yle: none;border: 0;padding: 0px;margin: 0px;font-family: 'Helvetica Neue L=
ight', Helvetica, Arial, sans-serif;-webkit-font-smoothing: antialiased;col=
or: #8899a6;font-size: 12px;font-weight: normal;line-height: 12px;text-deco=
ration:none;border-style:none;border:0;padding:0;margin:0;font-family:'Helv=
etica Neue Light', Helvetica, Arial, sans-serif;-webkit-font-smoothing:anti=
aliased;color:#8899a6;font-size:12px;padding:0px;margin:0px;font-weight:nor=
mal;line-height:12px;">Promote your top Tweets to drive sales.</a> </td>
</tr>
<tr>
<td height=3D"15" style=3D"padding: 0;margin: 0;line-height: 1px;font-size:=
 1px;padding:0;margin:0;line-height:1px;font-size:1px;"></td>
</tr>
</tbody>
</table>
<!--/////////////////// end pre-header///////////////////////////-->
<!--/////////////////// logo ///////////////////////////-->
<table class=3D"collapse" id=3D"header" align=3D"center" width=3D"680" styl=
e=3D"width: 680px;padding: 0;margin: 0;line-height: 1px;font-size: 1px;padd=
ing:0;margin:0;line-height:1px;font-size:1px;" bgcolor=3D"#ffffff" cellpadd=
ing=3D"0" cellspacing=3D"0" border=3D"0">
<tbody>
<tr>
<td style=3D"min-width: 680px;height: 1;padding: 0;margin: 0;line-height: 1=
px;font-size: 1px;padding:0;margin:0;line-height:1px;font-size:1px;" height=
=3D"1" class=3D"cut"> <img src=3D"https://ea.twimg.com/email/self_serve/med=
ia/spacer-1402696023930.png" height=3D"1" style=3D"min-width: 680px;height:=
 1px;margin: 0;padding: 0;display: block;-ms-interpolation-mode: bicubic;bo=
rder: none;outline: none;margin:0;padding:0;display:block;-ms-interpolation=
-mode:bicubic;border:none;outline:none;" /> </td>
</tr>
<tr>
<td height=3D"15" style=3D"height: 15px;padding: 0;margin: 0;line-height: 1=
px;font-size: 1px;padding:0;margin:0;line-height:1px;font-size:1px;" class=
=3D"logo_space">&nbsp; </td>
</tr>
<tr align=3D"center">
<td align=3D"center" style=3D"padding: 0;margin: 0;line-height: 1px;font-si=
ze: 1px;padding:0;margin:0;line-height:1px;font-size:1px;"> <a href=3D"http=
s://twitter.com/i/redirect?url=3Dhttps%3A%2F%2Fads.twitter.com%2Fstart%3Fut=
m_source%3Dlead_factory%26utm_medium%3Demail%26utm_content%3D11%26utm_campa=
ign%3Dacq_chain%26lang%3Den%26ref%3Dgb-em-tw-smbss_acq_chain_11-20161017-d&=
amp;t=3D1&amp;cn=3Dc21ic3NfYWNxX2NoYWluXzEx&amp;sig=3Db0fdd20f9a68d43797851=
38adb569f0fbbadf6f0&amp;iid=3Df52b5f4a487443728449c7b981489096&amp;uid=3D28=
104615&amp;nid=3D244+1554" target=3D"blank" style=3D"text-decoration: none;=
border-style: none;border: 0;padding: 0;margin: 0;text-decoration:none;bord=
er-style:none;border:0;padding:0;margin:0;"> <img width=3D"130" alt=3D"Twit=
ter for Business" align=3D"center" src=3D"http://img.en25.com/EloquaImages/=
clients/TwitterInc/{9612a8d0-e5d1-49a8-a880-963b7ba9b3fb}_Twitter-SMB-Logo_=
blue_horizontal_EN.png" style=3D"width: 130px;padding-bottom: 2px;margin: 0=
;padding: 0;display: block;-ms-interpolation-mode: bicubic;border: none;out=
line: none;margin:0;padding:0;display:block;-ms-interpolation-mode:bicubic;=
border:none;outline:none;" /> </a> </td>
</tr>
<tr>
<td height=3D"15" style=3D"height: 15px;padding: 0;margin: 0;line-height: 1=
px;font-size: 1px;padding:0;margin:0;line-height:1px;font-size:1px;" class=
=3D"logo_space">&nbsp; </td>
</tr>
</tbody>
</table>
<!--/////////////////// end logo///////////////////////////-->
<!--/////////////////// hero image ///////////////////////////-->
<table class=3D"collapse" id=3D"header" align=3D"center" width=3D"680" styl=
e=3D"width: 680px;background-color: #55acee;padding: 0;margin: 0;line-heigh=
t: 1px;font-size: 1px;padding:0;margin:0;line-height:1px;font-size:1px;" bg=
color=3D"#55acee" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tbody>
<tr>
<td style=3D"padding: 0;margin: 0;line-height: 1px;font-size: 1px;padding:0=
;margin:0;line-height:1px;font-size:1px;"> <a href=3D"https://twitter.com/i=
/redirect?url=3Dhttps%3A%2F%2Fads.twitter.com%2Fstart%3Futm_source%3Dlead_f=
actory%26utm_medium%3Demail%26utm_content%3D11%26utm_campaign%3Dacq_chain%2=
6lang%3Den%26ref%3Dgb-em-tw-smbss_acq_chain_11-20161017-d&amp;t=3D1&amp;cn=
=3Dc21ic3NfYWNxX2NoYWluXzEx&amp;sig=3D5226920f066f934cf65ee661dd2c05a1b88cb=
a9b&amp;iid=3Df52b5f4a487443728449c7b981489096&amp;uid=3D28104615&amp;nid=
=3D244+1555" style=3D"text-decoration: none;border-style: none;border: 0;pa=
dding: 0;margin: 0;text-decoration:none;border-style:none;border:0;padding:=
0;margin:0;"> <img src=3D"http://img.en25.com/EloquaImages/clients/TwitterI=
nc/%7bee905397-8185-4e43-995c-1c6d5a79f641%7d_smbss_acq_chain_11.jpg" width=
=3D"680" class=3D"media" alt=3D"Twitter for Business" style=3D"font-family:=
 'Helvetica Neue Light', Helvetica, Arial, sans-serif;-webkit-font-smoothin=
g: antialiased;-webkit-text-size-adjust: none;color: #ffffff;font-size: 50p=
x;font-weight: 300;text-align: center;background-color: #3b94d9;margin: 0px=
;padding: 0px;display: block;-ms-interpolation-mode: bicubic;border: none;o=
utline: none;margin:0;padding:0;display:block;-ms-interpolation-mode:bicubi=
c;border:none;outline:none;padding:0px;margin:0px;background-color:#8899a6;=
text-align:center;" /> </a> </td>
</tr>
</tbody>
</table>
<!--/////////////////// end hero image ///////////////////////////-->
<!--//////////////////// header copy //////////////////////////-->
<table class=3D"collapse" align=3D"center" width=3D"680" style=3D"width: 68=
0px;background-color: #ffffff;border-bottom: 2px solid #f5f8fa;padding: 0;m=
argin: 0;line-height: 1px;font-size: 1px;padding:0;margin:0;line-height:1px=
;font-size:1px;" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tbody>
<tr>
<td width=3D"90" style=3D"width: 90px;padding: 0;margin: 0;line-height: 1px=
;font-size: 1px;padding:0;margin:0;line-height:1px;font-size:1px;" class=3D=
"margins"></td>
<td align=3D"center" style=3D"padding: 0;margin: 0;line-height: 1px;font-si=
ze: 1px;padding:0;margin:0;line-height:1px;font-size:1px;">
<table width=3D"100%" align=3D"left" cellpadding=3D"0" cellspacing=3D"0" bo=
rder=3D"0" class=3D"collapse" style=3D"padding: 0;margin: 0;line-height: 1p=
x;font-size: 1px;padding:0;margin:0;line-height:1px;font-size:1px;">
<tbody>
<tr>
<td height=3D"40" style=3D"height: 40px;padding: 0;margin: 0;line-height: 1=
px;font-size: 1px;padding:0;margin:0;line-height:1px;font-size:1px;" class=
=3D"main-unit-height"></td>
</tr>
<tr>
<td class=3D"h1_header" style=3D"padding: 0px;margin: 0px;line-height: 40px=
;font-size: 30px;font-family: 'Helvetica Neue Light', Helvetica, Arial, san=
s-serif;-webkit-font-smoothing: antialiased;-webkit-text-size-adjust: none;=
color: #66757f;font-weight: 300;text-align: center;padding:0;margin:0;line-=
height:1px;font-size:1px;font-family:'Helvetica Neue Light', Helvetica, Ari=
al, sans-serif;-webkit-font-smoothing:antialiased;-webkit-text-size-adjust:=
none;color:#66757f;font-size:30px;padding:0px;margin:0px;font-weight:300;li=
ne-height:40px;text-align:center;"> Reach more potential customers </td>
</tr>
<tr>
<td height=3D"26" style=3D"height: 26px;padding: 0;margin: 0;line-height: 1=
px;font-size: 1px;padding:0;margin:0;line-height:1px;font-size:1px;"></td>
</tr>
<!--*********** button ************-->
<tr>
<td align=3D"center" style=3D"padding: 0;margin: 0;line-height: 1px;font-si=
ze: 1px;padding:0;margin:0;line-height:1px;font-size:1px;">
<table style=3D"padding: 0;margin: 0;line-height: 1px;font-size: 1px;paddin=
g:0;margin:0;line-height:1px;font-size:1px;">
<tbody>
<tr>
<td style=3D"padding: 0;margin: 0;line-height: 1px;font-size: 1px;padding:0=
;margin:0;line-height:1px;font-size:1px;">
<!-- Tap, click, press, push the button -->
<table width=3D"100%" border=3D"0" cellspacing=3D"0" cellpadding=3D"0" styl=
e=3D"padding: 0;margin: 0;line-height: 1px;font-size: 1px;padding:0;margin:=
0;line-height:1px;font-size:1px;">
<tbody>
<tr>
<td style=3D"padding: 0;margin: 0;line-height: 1px;font-size: 1px;padding:0=
;margin:0;line-height:1px;font-size:1px;">
<table border=3D"0" cellspacing=3D"0" cellpadding=3D"0" style=3D"padding: 0=
;margin: 0;line-height: 1px;font-size: 1px;padding:0;margin:0;line-height:1=
px;font-size:1px;">
<tbody>
<tr>
<td align=3D"center" class=3D"bulletproof-btn-1" bgcolor=3D"#55acee" style=
=3D"padding: 0;margin: 0;line-height: 18px;font-size: 1px;-webkit-border-ra=
dius: 4px;-moz-border-radius: 4px;border-radius: 4px;padding:0;margin:0;lin=
e-height:1px;font-size:1px;-webkit-border-radius:4px;-moz-border-radius:4px=
;border-radius:4px;line-height:18px;"> <a href=3D"https://twitter.com/i/red=
irect?url=3Dhttps%3A%2F%2Fanalytics.twitter.com%2Fuser%2F*%2Ftweets%3Ffilte=
r%3Dtop%26utm_source%3Dlead_factory%26utm_medium%3Demail%26utm_content%3D11=
%26utm_campaign%3Dacq_chain%26ref%3Dgb-em-tw-smbss_acq_chain_11-20161017-d&=
amp;t=3D1&amp;cn=3Dc21ic3NfYWNxX2NoYWluXzEx&amp;sig=3De2bb1fe6305bf47aa52f4=
10a85576540e64d4680&amp;iid=3Df52b5f4a487443728449c7b981489096&amp;uid=3D28=
104615&amp;nid=3D244+1556" target=3D"_blank" class=3D"bulletproof-btn-2" st=
yle=3D"text-decoration: none;border-style: none;border: 1px solid #55acee;p=
adding: 11px 30px;margin: 0;font-size: 16px;font-family: 'Helvetica Neue', =
Helvetica, Arial, sans-serif;color: #ffffff;-webkit-border-radius: 4px;-moz=
-border-radius: 4px;border-radius: 4px;display: inline-block;font-weight: b=
old;-webkit-font-smoothing: antialiased;text-decoration:none;border-style:n=
one;border:0;padding:0;margin:0;font-size:16px;font-family:'Helvetica Neue'=
, Helvetica, Arial, sans-serif;color:#ffffff;text-decoration:none;-webkit-b=
order-radius:4px;-moz-border-radius:4px;border-radius:4px;padding:11px 30px=
;border:1px solid #55acee;display:inline-block;font-weight:bold;-webkit-fon=
t-smoothing:antialiased;">
<!--[if gte mso 11]>&nbsp; &nbsp; &nbsp;<![endif]--> Try quick promote
<!--[if gte mso 11]>&nbsp; &nbsp; &nbsp;<![endif]--> </a> </td>
</tr>
</tbody>
</table> </td>
</tr>
</tbody>
</table> </td>
</tr>
</tbody>
</table> </td>
</tr>
<!--*********** end button ************-->
</tbody>
</table> </td>
<td width=3D"90" style=3D"width: 90px;padding: 0;margin: 0;line-height: 1px=
;font-size: 1px;padding:0;margin:0;line-height:1px;font-size:1px;" class=3D=
"margins"></td>
</tr>
<tr>
<td colspan=3D"3" height=3D"50" style=3D"height: 50px;padding: 0;margin: 0;=
line-height: 1px;font-size: 1px;padding:0;margin:0;line-height:1px;font-siz=
e:1px;" class=3D"btm-unit-height3"></td>
</tr>
</tbody>
</table>
<!--//////////////////// end header copy //////////////////////////-->
<!--//////////////////// body text //////////////////////////-->
<table class=3D"collapse" align=3D"center" width=3D"680" style=3D"width: 68=
0px;background-color: #ffffff;padding: 0;margin: 0;line-height: 1px;font-si=
ze: 1px;padding:0;margin:0;line-height:1px;font-size:1px;" cellpadding=3D"0=
" cellspacing=3D"0" border=3D"0">
<tbody>
<tr>
<td width=3D"90" style=3D"width: 90px;padding: 0;margin: 0;line-height: 1px=
;font-size: 1px;padding:0;margin:0;line-height:1px;font-size:1px;" class=3D=
"margins"></td>
<td align=3D"center" style=3D"padding: 0;margin: 0;line-height: 1px;font-si=
ze: 1px;padding:0;margin:0;line-height:1px;font-size:1px;">
<table width=3D"100%" align=3D"left" cellpadding=3D"0" cellspacing=3D"0" bo=
rder=3D"0" class=3D"collapse" style=3D"padding: 0;margin: 0;line-height: 1p=
x;font-size: 1px;padding:0;margin:0;line-height:1px;font-size:1px;">
<tbody>
<tr>
<td height=3D"40" style=3D"height: 40px;padding: 0;margin: 0;line-height: 1=
px;font-size: 1px;padding:0;margin:0;line-height:1px;font-size:1px;" class=
=3D"main-unit-height"></td>
</tr>
<tr>
<td class=3D"h1" style=3D"padding: 0px;margin: 0px;line-height: 30px;font-s=
ize: 20px;font-family: 'Helvetica Neue Light', Helvetica, Arial, sans-serif=
;-webkit-font-smoothing: antialiased;-webkit-text-size-adjust: none;color: =
#66757f;font-weight: 300;text-align: left;padding:0;margin:0;line-height:1p=
x;font-size:1px;font-family:'Helvetica Neue Light', Helvetica, Arial, sans-=
serif;-webkit-font-smoothing:antialiased;-webkit-text-size-adjust:none;colo=
r:#66757f;font-size:20px;padding:0px;margin:0px;font-weight:300;line-height=
:30px;text-align:left;"> Hi @atechmedia </td>
</tr>
<tr>
<td height=3D"25" style=3D"padding: 0;margin: 0;line-height: 1px;font-size:=
 1px;padding:0;margin:0;line-height:1px;font-size:1px;"></td>
</tr>
<!-- ***** recap ***** -->
<tr align=3D"left">
<td align=3D"left" class=3D"body-text" style=3D"padding: 0px;margin: 0px;li=
ne-height: 28px;font-size: 19px;font-family: 'Helvetica Neue Light', Helvet=
ica, Arial, sans-serif;-webkit-font-smoothing: antialiased;-webkit-text-siz=
e-adjust: none;color: #8899a6;font-weight: 300;text-align: left;padding:0;m=
argin:0;line-height:1px;font-size:1px;font-family:'Helvetica Neue Light', H=
elvetica, Arial, sans-serif;-webkit-font-smoothing:antialiased;-webkit-text=
-size-adjust:none;color:#8899a6;font-size:19px;padding:0px;margin:0px;font-=
weight:300;line-height:28px;text-align:left;"> Running a business is hard w=
ork. That=E2=80=99s why Twitter Ads makes it easy and fast for you to get y=
our best-performing Tweets in front of more potential customers with quick =
promote.<br /><br /> Research shows that over half of the users who follow =
small to medium sized businesses notice Twitter ads, and the majority of th=
ose who notice take action as a result.*<br /><br /> You can even promote a=
 Tweet from your iOS or Android device while on the go =E2=80=94 it=E2=80=
=99s that simple. Just select your top Tweet from your Tweet activity dashb=
oard to get started.<br /><br /> </td>
</tr>
<tr align=3D"center">
<td align=3D"center" class=3D"body-text-center" style=3D"padding: 0px;margi=
n: 0px;line-height: 28px;font-size: 16px;font-family: 'Helvetica Neue Light=
', Helvetica, Arial, sans-serif;-webkit-font-smoothing: antialiased;-webkit=
-text-size-adjust: none;color: #8899a6;font-weight: 700;text-align: center;=
padding:0;margin:0;line-height:1px;font-size:1px;font-family:'Helvetica Neu=
e Light', Helvetica, Arial, sans-serif;-webkit-font-smoothing:antialiased;-=
webkit-text-size-adjust:none;color:#8899a6;font-size:19px;padding:0px;margi=
n:0px;font-weight:700;line-height:28px;text-align:center;"> <strong>REACH N=
EW CUSTOMERS WITH QUICK PROMOTE TODAY.</strong> </td>
</tr>
<!-- ***** end recap ***** -->
</tbody>
</table> </td>
<td width=3D"90" style=3D"width: 90px;padding: 0;margin: 0;line-height: 1px=
;font-size: 1px;padding:0;margin:0;line-height:1px;font-size:1px;" class=3D=
"margins"></td>
</tr>
<tr>
<td colspan=3D"3" height=3D"20" style=3D"height: 20px;padding: 0;margin: 0;=
line-height: 1px;font-size: 1px;padding:0;margin:0;line-height:1px;font-siz=
e:1px;" class=3D"btm-unit-height2"></td>
</tr>
</tbody>
</table>
<!--//////////////////// end text //////////////////////////-->
<!--//////////////////// body text //////////////////////////-->
<table class=3D"collapse" align=3D"center" width=3D"680" style=3D"width: 68=
0px;background-color: #ffffff;padding: 0;margin: 0;line-height: 1px;font-si=
ze: 1px;padding:0;margin:0;line-height:1px;font-size:1px;" cellpadding=3D"0=
" cellspacing=3D"0" border=3D"0">
<tbody>
<tr>
<td width=3D"90" style=3D"width: 90px;padding: 0;margin: 0;line-height: 1px=
;font-size: 1px;padding:0;margin:0;line-height:1px;font-size:1px;" class=3D=
"margins"></td>
<td align=3D"center" style=3D"padding: 0;margin: 0;line-height: 1px;font-si=
ze: 1px;padding:0;margin:0;line-height:1px;font-size:1px;">
<table width=3D"100%" align=3D"left" cellpadding=3D"0" cellspacing=3D"0" bo=
rder=3D"0" class=3D"collapse" style=3D"padding: 0;margin: 0;line-height: 1p=
x;font-size: 1px;padding:0;margin:0;line-height:1px;font-size:1px;">
<tbody>
<tr>
<td height=3D"20" style=3D"height: 20px;padding: 0;margin: 0;line-height: 1=
px;font-size: 1px;padding:0;margin:0;line-height:1px;font-size:1px;"></td>
</tr>
<!--*********** button ************-->
<tr>
<td align=3D"center" style=3D"padding: 0;margin: 0;line-height: 1px;font-si=
ze: 1px;padding:0;margin:0;line-height:1px;font-size:1px;">
<table style=3D"padding: 0;margin: 0;line-height: 1px;font-size: 1px;paddin=
g:0;margin:0;line-height:1px;font-size:1px;">
<tbody>
<tr>
<td style=3D"padding: 0;margin: 0;line-height: 1px;font-size: 1px;padding:0=
;margin:0;line-height:1px;font-size:1px;">
<!-- Tap, click, press, push the button -->
<table width=3D"100%" border=3D"0" cellspacing=3D"0" cellpadding=3D"0" styl=
e=3D"padding: 0;margin: 0;line-height: 1px;font-size: 1px;padding:0;margin:=
0;line-height:1px;font-size:1px;">
<tbody>
<tr>
<td style=3D"padding: 0;margin: 0;line-height: 1px;font-size: 1px;padding:0=
;margin:0;line-height:1px;font-size:1px;">
<table border=3D"0" cellspacing=3D"0" cellpadding=3D"0" style=3D"padding: 0=
;margin: 0;line-height: 1px;font-size: 1px;padding:0;margin:0;line-height:1=
px;font-size:1px;">
<tbody>
<tr>
<td align=3D"center" class=3D"bulletproof-btn-1" bgcolor=3D"#55acee" style=
=3D"padding: 0;margin: 0;line-height: 18px;font-size: 1px;-webkit-border-ra=
dius: 4px;-moz-border-radius: 4px;border-radius: 4px;padding:0;margin:0;lin=
e-height:1px;font-size:1px;-webkit-border-radius:4px;-moz-border-radius:4px=
;border-radius:4px;line-height:18px;"> <a href=3D"https://twitter.com/i/red=
irect?url=3Dhttps%3A%2F%2Fbusiness.twitter.com%2Fen%2Fadvertising%2Fcampaig=
n-types%2Fquick-promote.html%3Futm_source%3Dlead_factory%26utm_medium%3Dema=
il%26utm_content%3D11%26utm_campaign%3Dacq_chain%26ref%3Dgb-em-tw-smbss_acq=
_chain_11-20161017-d&amp;t=3D1&amp;cn=3Dc21ic3NfYWNxX2NoYWluXzEx&amp;sig=3D=
b105016c4ab1cf7eb70975463076e07125438f65&amp;iid=3Df52b5f4a487443728449c7b9=
81489096&amp;uid=3D28104615&amp;nid=3D244+1557" target=3D"_blank" class=3D"=
bulletproof-btn-2" style=3D"text-decoration: none;border-style: none;border=
: 1px solid #55acee;padding: 11px 30px;margin: 0;font-size: 16px;font-famil=
y: 'Helvetica Neue', Helvetica, Arial, sans-serif;color: #ffffff;-webkit-bo=
rder-radius: 4px;-moz-border-radius: 4px;border-radius: 4px;display: inline=
-block;font-weight: bold;-webkit-font-smoothing: antialiased;text-decoratio=
n:none;border-style:none;border:0;padding:0;margin:0;font-size:16px;font-fa=
mily:'Helvetica Neue', Helvetica, Arial, sans-serif;color:#ffffff;text-deco=
ration:none;-webkit-border-radius:4px;-moz-border-radius:4px;border-radius:=
4px;padding:11px 30px;border:1px solid #55acee;display:inline-block;font-we=
ight:bold;-webkit-font-smoothing:antialiased;">
<!--[if gte mso 11]>&nbsp; &nbsp; &nbsp;<![endif]--> See more
<!--[if gte mso 11]>&nbsp; &nbsp; &nbsp;<![endif]--> </a> </td>
</tr>
</tbody>
</table> </td>
</tr>
</tbody>
</table> </td>
</tr>
</tbody>
</table> </td>
</tr>
<!--*********** end button ************-->
<tr>
<td class=3D"body-text" style=3D"line-height: 24px;font-size: 13px;padding:=
0;margin:0;line-height:1px;font-size:1px;font-family:'Helvetica Neue Light'=
, Helvetica, Arial, sans-serif;-webkit-font-smoothing:antialiased;-webkit-t=
ext-size-adjust:none;color:#8899a6;font-size:19px;padding:0px;margin:0px;fo=
nt-weight:300;line-height:28px;text-align:left;"> <br />*Twitter + DB5 =E2=
=80=9CSmall Business Customer Insights Study,=E2=80=9D U.S. 2014 </td>
</tr>
</tbody>
</table> </td>
<td width=3D"90" style=3D"width: 90px;padding: 0;margin: 0;line-height: 1px=
;font-size: 1px;padding:0;margin:0;line-height:1px;font-size:1px;" class=3D=
"margins"></td>
</tr>
<tr>
<td colspan=3D"3" height=3D"70" style=3D"height: 70px;padding: 0;margin: 0;=
line-height: 1px;font-size: 1px;padding:0;margin:0;line-height:1px;font-siz=
e:1px;" class=3D"btm-unit-height3"></td>
</tr>
</tbody>
</table>
<!--//////////////////// end text //////////////////////////-->
<!--///////////////////// footer /////////////////////-->
<table class=3D"collapse" id=3D"footer" align=3D"center" width=3D"680" styl=
e=3D"width: 680px;background-color: #ffffff;padding: 0;margin: 0;line-heigh=
t: 1px;font-size: 1px;padding:0;margin:0;line-height:1px;font-size:1px;" ce=
llpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tbody>
<tr>
<td height=3D"1" style=3D"line-height: 1px;display: block;height: 1px;backg=
round-color: #e1e8ed;padding: 0;margin: 0;font-size: 1px;padding:0;margin:0=
;line-height:1px;font-size:1px;"></td>
</tr>
<tr>
<td height=3D"30" style=3D"height: 30;padding: 0;margin: 0;line-height: 1px=
;font-size: 1px;padding:0;margin:0;line-height:1px;font-size:1px;"></td>
</tr>
<tr>
<td align=3D"center" style=3D"padding: 0;margin: 0;line-height: 1px;font-si=
ze: 1px;padding:0;margin:0;line-height:1px;font-size:1px;"> <span class=3D"=
footer_type" style=3D"font-family: 'Helvetica Neue Light', Helvetica, Arial=
, sans-serif;-webkit-font-smoothing: antialiased;color: #8899a6;font-size: =
12px;padding: 0px;margin: 0px;font-weight: normal;line-height: 12px;font-fa=
mily:'Helvetica Neue Light', Helvetica, Arial, sans-serif;-webkit-font-smoo=
thing:antialiased;color:#8899a6;font-size:12px;padding:0px;margin:0px;font-=
weight:normal;line-height:12px;"> <a href=3D"https://twitter.com/i/redirect=
?url=3Dhttps%3A%2F%2Fbusiness.twitter.com%3Futm_source%3Dlead_factory%26utm=
_medium%3Demail%26utm_content%3D11%26utm_campaign%3Dacq_chain%26lang%3Den%2=
6ref%3Dgb-em-tw-smbss_acq_chain_11-20161017-d&amp;t=3D1&amp;cn=3Dc21ic3NfYW=
NxX2NoYWluXzEx&amp;sig=3D46505926c5bbf240955f90c74600d01448ec108f&amp;iid=
=3Df52b5f4a487443728449c7b981489096&amp;uid=3D28104615&amp;nid=3D244+1558" =
class=3D"footer_link" style=3D"text-decoration: none;border-style: none;bor=
der: 0;padding: 0px;margin: 0px;font-family: 'Helvetica Neue Light', Helvet=
ica, Arial, sans-serif;-webkit-font-smoothing: antialiased;-webkit-text-siz=
e-adjust: none;color: #55acee;font-size: 12px;font-weight: 600;line-height:=
 12px;text-decoration:none;border-style:none;border:0;padding:0;margin:0;fo=
nt-family:'Helvetica Neue Light', Helvetica, Arial, sans-serif;-webkit-font=
-smoothing:antialiased;-webkit-text-size-adjust:none;color:#55acee;font-siz=
e:12px;padding:0px;margin:0px;font-weight:600;line-height:12px;">business.t=
witter.com</a>&nbsp;|&nbsp; <a href=3D"https://twitter.com/i/redirect?url=
=3Dhttp%3A%2F%2Fwww.twitter.com%2FTwitterBusiness%3Futm_source%3Dlead_facto=
ry%26utm_medium%3Demail%26utm_content%3D11%26utm_campaign%3Dacq_chain&amp;t=
=3D1&amp;cn=3Dc21ic3NfYWNxX2NoYWluXzEx&amp;sig=3D0c0493cc223e2e4b9020c43ae6=
f4ded9c12551e1&amp;iid=3Df52b5f4a487443728449c7b981489096&amp;uid=3D2810461=
5&amp;nid=3D244+1559" class=3D"footer_link" style=3D"text-decoration: none;=
border-style: none;border: 0;padding: 0px;margin: 0px;font-family: 'Helveti=
ca Neue Light', Helvetica, Arial, sans-serif;-webkit-font-smoothing: antial=
iased;-webkit-text-size-adjust: none;color: #55acee;font-size: 12px;font-we=
ight: 600;line-height: 12px;text-decoration:none;border-style:none;border:0=
;padding:0;margin:0;font-family:'Helvetica Neue Light', Helvetica, Arial, s=
ans-serif;-webkit-font-smoothing:antialiased;-webkit-text-size-adjust:none;=
color:#55acee;font-size:12px;padding:0px;margin:0px;font-weight:600;line-he=
ight:12px;">@TwitterBusiness</a>&nbsp;|&nbsp; <a href=3D"https://twitter.co=
m/i/redirect?url=3Dhttp%3A%2F%2Fbusiness.twitter.com%2Fhelp%3Futm_source%3D=
lead_factory%26utm_medium%3Demail%26utm_content%3D11%26utm_campaign%3Dacq_c=
hain&amp;t=3D1&amp;cn=3Dc21ic3NfYWNxX2NoYWluXzEx&amp;sig=3Da04c11e7ed134ebb=
ca429a2c5429f7240fcab776&amp;iid=3Df52b5f4a487443728449c7b981489096&amp;uid=
=3D28104615&amp;nid=3D244+1560" class=3D"footer_link" style=3D"text-decorat=
ion: none;border-style: none;border: 0;padding: 0px;margin: 0px;font-family=
: 'Helvetica Neue Light', Helvetica, Arial, sans-serif;-webkit-font-smoothi=
ng: antialiased;-webkit-text-size-adjust: none;color: #55acee;font-size: 12=
px;font-weight: 600;line-height: 12px;text-decoration:none;border-style:non=
e;border:0;padding:0;margin:0;font-family:'Helvetica Neue Light', Helvetica=
, Arial, sans-serif;-webkit-font-smoothing:antialiased;-webkit-text-size-ad=
just:none;color:#55acee;font-size:12px;padding:0px;margin:0px;font-weight:6=
00;line-height:12px;">Support</a> </span> </td>
</tr>
<tr>
<td height=3D"10" style=3D"height: 10px;line-height: 1px;font-size: 1px;pad=
ding: 0;margin: 0;padding:0;margin:0;line-height:1px;font-size:1px;"></td>
</tr>
<tr>
<td align=3D"center" style=3D"padding: 0;margin: 0;line-height: 1px;font-si=
ze: 1px;padding:0;margin:0;line-height:1px;font-size:1px;"> <span class=3D"=
address"> <p style=3D"text-decoration: none;border-style: none;border: 0;pa=
dding: 0px;margin: 0px;font-family: 'Helvetica Neue Light', Helvetica, Aria=
l, sans-serif;-webkit-font-smoothing: antialiased;color: #8899a6;font-size:=
 12px;font-weight: normal;line-height: 12px;cursor: default;"><strong>Twitt=
er, Inc.</strong> 1355 Market Street, Suite 900, San Francisco, CA 94103</p=
> </span> </td>
</tr>
<tr>
<td height=3D"10" style=3D"height: 10px;line-height: 1px;font-size: 1px;pad=
ding: 0;margin: 0;padding:0;margin:0;line-height:1px;font-size:1px;"></td>
</tr>
<tr>
<td align=3D"center" style=3D"padding: 0;margin: 0;line-height: 1px;font-si=
ze: 1px;padding:0;margin:0;line-height:1px;font-size:1px;"> <span class=3D"=
footer_type" style=3D"font-family: 'Helvetica Neue Light', Helvetica, Arial=
, sans-serif;-webkit-font-smoothing: antialiased;color: #8899a6;font-size: =
12px;padding: 0px;margin: 0px;font-weight: normal;line-height: 12px;font-fa=
mily:'Helvetica Neue Light', Helvetica, Arial, sans-serif;-webkit-font-smoo=
thing:antialiased;color:#8899a6;font-size:12px;padding:0px;margin:0px;font-=
weight:normal;line-height:12px;"> <a href=3D"https://twitter.com/i/u?t=3D1&=
amp;cn=3Dc21ic3NfYWNxX2NoYWluXzEx&amp;sig=3D7b7b93c2d03f574c665d495688b2d96=
fa5cac763&amp;iid=3Df52b5f4a487443728449c7b981489096&amp;uid=3D28104615&amp=
;nid=3D244+26&amp;usbid=3D30" class=3D"footer_link" style=3D"text-decoratio=
n: none;border-style: none;border: 0;padding: 0px;margin: 0px;font-family: =
'Helvetica Neue Light', Helvetica, Arial, sans-serif;-webkit-font-smoothing=
: antialiased;-webkit-text-size-adjust: none;color: #55acee;font-size: 12px=
;font-weight: 600;line-height: 12px;text-decoration:none;border-style:none;=
border:0;padding:0;margin:0;font-family:'Helvetica Neue Light', Helvetica, =
Arial, sans-serif;-webkit-font-smoothing:antialiased;-webkit-text-size-adju=
st:none;color:#55acee;font-size:12px;padding:0px;margin:0px;font-weight:600=
;line-height:12px;">Unsubscribe</a> </span> </td>
</tr>
<tr>
<td height=3D"40" style=3D"height: 40;padding: 0;margin: 0;line-height: 1px=
;font-size: 1px;padding:0;margin:0;line-height:1px;font-size:1px;"></td>
</tr>
</tbody>
</table>
<!--///////////////////// end footer /////////////////////--> </td>
</tr>
</tbody>
</table>
<div style=3D"display:none; white-space:nowrap; font:15px courier; color:#f=
fffff;">
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
</div>
<img width=3D"1" height=3D"1" style=3D"display: block;margin:0;padding:0;di=
splay:block;-ms-interpolation-mode:bicubic;border:none;outline:none;" src=
=3D"https://twitter.com/scribe/ibis?t=3D1&amp;cn=3Dc21ic3NfYWNxX2NoYWluXzEx=
&amp;iid=3Df52b5f4a487443728449c7b981489096&amp;uid=3D28104615&amp;nid=3D24=
4+20" />
</body>
</html>

------=_Part_20209459_199831831.1476695299532--
