domain: adamtest.viaduct.io
time: 1627490307
dkim_identifier: postal-R7w1LN
private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIICWwIBAAKBgQCwc2EEPeNKe1jS4cQ0GQXeRkm8vsDsD3UeR9EUdxLuvbzJ2VvZ
  tRyFVLkUMmQ0WjOLZ+DU3u4CjfGp/xuNDJROmYd3itz7FKRxvOIGCYwu7ka5GSqP
  V/aXyWRWalbo5RPbjfImnHGkKzYlTzvd7p+MkhY+0pCeXnWDWD9IVcGHjQIDAQAB
  AoGAJj98Yi0AHd8K6/tgSmK6MOpPhYhbzU+0dXHf0m3VPscGK0LgdBqcKhKpY8Vg
  jzCWR7umsr34HbmjDtRrpnF5nAuoevuK0CYI5a2u2fnc1Qygq4M3Ydq4MtKDA2Fs
  i6b+h+DUpn2YRX1fYLAVIwJiRi0qYuDX63BdT0jsuaQyRAkCQQDlK+NTpVY3A1tu
  wncAmax3gap3fmapZOEGhKIK+zHP3w13gztQdjcJ6v/5RMemiqYTKJcrlCEYFYGF
  z94JvUs3AkEAxRt8gA9kQ8l1VcpdGurRAduCG/raeIrpD9MXlfY9c8+V+65mVjQ+
  WuhbJ6fQHkA2MVuUWR+EJ1SELbDtgYoNWwJAGKxw/UB/18x0u6gUR+xDtVowkEz7
  oKFL2PfOun/xDQBm4scuS6tuoZK7nIrbNAMZflaQcBCyv3URTObkcQgAYQJACG4j
  hgqifC+6n/+2ubb/V3f++ZliDLPMQgwCPzy35iMjxA7ye49id1rmwyxvP0v5xWSo
  VKN/cHsx6A5gKiEwbwJAV1Ll5Xqfj6p92rSXXP/cHG5cEvYFsPgYRPMd6qgVRvoQ
  8CZWA1vhnm6M/tB7UExROAuqexsDrOlTPrphLEcMdg==
  -----END RSA PRIVATE KEY-----
headers: content-transfer-encoding:content-type:to:message-id:date:mime-version:reply-to:from:subject:list-unsubscribe:list-id
bh: z/984HsxoQhYgMjcdqgVI00vVOHB5H85L6FE9/7IG3k=
b: AUgfU59IxHLLciftQ6eTuCabZp6ui5BoKxbfhN31yCR7YqRQM3I3vVxfu653zztyC2LbWVZ1oLPSCD/UlDKRtqWUtjXrI/br+7SmMRwv4VyCzpVeXp25w+f6UR1Y8VGdfh/Q2sfqZ1Sop5g6DdGpv1m5abKJ3/onX6vt79ZIMwA=
---
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html; charset="UTF-8"
To: gf1gzhnlUUZ3Zo@dkimvalidator.com
Message-ID: <E6.0E.26872.BB6E0016@af.mta3vrest.cc.prd.sparkpost>
Date: Wed, 28 Jul 2021 05:10:19 +0000
MIME-Version: 1.0
Reply-To: mail@reply.perfect-quotes.com
From: "Birchmore Property" <adam@adamtest.viaduct.io>
Subject: Hassle-free buy-to-let opportunity with 8.5% NET returns
X-Report-Abuse: mail@reply.perfect-quotes.com
List-Unsubscribe: <mailto:unsubscribe@eu.sparkpostmail.com?subject=unsubscribe:pkMQwULJsqLL5bsTqDUpVjnB2gV0VDtO-6Q6tkEtuRo~|eyAicmNwdF90byI6ICJ0ZWFtQG9yaWVudG8udWsiLCAidGVuYW50X2lkIjogInNwY2V1IiwgImN1c3RvbWVyX2lkIjogIjExMDAxIiwgIm1lc3NhZ2VfaWQiOiAiNjEwMGJiZTYwMDYxMmUxMjZlZTAiLCAic3ViYWNjb3VudF9pZCI6ICIwIiB9>
List-Id: <spceu.11001.0.sparkpostmail.com>

<html xmlns=3D"http://www.w3.org/1999/xhtml" xmlns:v=3D"urn:schemas-micro=
soft-com:vml" xmlns:o=3D"urn:schemas-microsoft-com:office:office" style=3D=
"padding:0;width:100%;background-color:#f8f8f8;margin:0;">
<head><meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3DU=
TF-8">
<!-- NAME: 1:3 COLUMN -->
<!--[if gte mso 15]>
    <xml>
      <o:OfficeDocumentSettings>
        <o:AllowPNG />
        <o:PixelsPerInch>96</o:PixelsPerInch>
      </o:OfficeDocumentSettings>
    </xml>
    <![endif]-->
<meta charset=3D"UTF-8">
<meta http-equiv=3D"x-ua-compatible" content=3D"IE=3Dedge">
<meta name=3D"viewport" content=3D"width=3Ddevice-width, initial-scale=3D=
1">
<link href=3D"https://fonts.googleapis.com/css2?family=3DPoppins:ital,wgh=
t@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300=
;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=3Dswap" rel=3D"styleshee=
t">
<style type=3D"text/css">
p {
	margin: 10px 0;
	padding: 0;
}
table {
	border-collapse: collapse;
}
h1, h2, h3, h4, h5, h6 {
	display: block;
	margin: 0;
	padding: 0;
}
img, a img {
	border: 0;
	height: auto;
	outline: none;
	text-decoration: none;
}
body, #bodyTable, #bodyCell {
	margin: 0;
	padding: 0;
	width: 100%;
}
.mcnPreviewText {
	display: none !important;
}
#outlook a {
	padding: 0;
}
img {
	-ms-interpolation-mode: bicubic;
}
table {
	mso-table-lspace: 0;
	mso-table-rspace: 0;
}
.ReadMsgBody {
	width: 100%;
}
.ExternalClass {
	width: 100%;
}
p, a, li, td, blockquote {
	mso-line-height-rule: exactly;
}
a[href^=3Dtel], a[href^=3Dsms] {
	color: inherit;
	cursor: default;
	text-decoration: none;
}
p, a, li, td, body, table, blockquote {
	-ms-text-size-adjust: 100%;
	-webkit-text-size-adjust: 100%;
}
.ExternalClass, .ExternalClass p, .ExternalClass td, .ExternalClass div, =
.ExternalClass span, .ExternalClass font {
	line-height: 100%;
}
a[x-apple-data-detectors] {
	color: inherit !important;
	text-decoration: none !important;
	font-size: inherit !important;
	font-family: inherit !important;
	font-weight: inherit !important;
	line-height: inherit !important;
}
#bodyCell {
	padding: 10px;
}
.templateContainer {
	max-width: 640px !important;
}
 [style*=3DPoppins] {
 font-family:'Poppins', Arial, sans-serif !important;
}
.ReadMsgBody {
	width: 100%;
	background-color: #f8f8f8;
}
.ExternalClass {
	width: 100%;
	background-color: #f8f8f8;
}
.templateContainer {
	max-width: 640px !important;
}
.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass fon=
t, .ExternalClass td, .ExternalClass div {
	line-height: 100%;
}
#outlook a {
	padding: 0;
}
html {
	width: 100%;
}
body, #bodyTable, #bodyCell {
	margin: 0;
	padding: 0;
	width: 100%;
}
html, body {
	background-color: #f8f8f8;
	margin: 0;
	padding: 0;
}
table {
	border-spacing: 0;
}
table td {
	border-collapse: collapse;
}
br, strong br, b br, em br, i br {
	line-height: 100%;
}
h1, h2, h3, h4, h5, h6 {
	line-height: 100% !important;
	-webkit-font-smoothing: antialiased;
}
img {
	height: auto !important;
	line-height: 100%;
	outline: none;
	text-decoration: none;
	display: block !important;
}
span a {
	color: #7a8b89 !important;
	text-decoration: none !important;
}
a {
	text-decoration: none !important;
}
.whitebutton a {
	color: #ffffff !important;
	text-decoration: underline !important;
}
.footer a {
	text-decoration: none !important;
}
table p {
	margin: 0;
}
.yshortcuts, .yshortcuts a, .yshortcuts a:link, .yshortcuts a:visited, .y=
shortcuts a:hover, .yshortcuts a span {
	text-decoration: none !important;
	border-bottom: none !important;
}
table {
	mso-table-lspace: 0;
	mso-table-rspace: 0;
}
img {
	-ms-interpolation-mode: bicubic;
}
body {
	-webkit-text-size-adjust: 100%;
}
body {
	-ms-text-size-adjust: 100%;
}
img {
	height: auto !important;
}
.hide_on_mobile {
}
 @media only screen and (max-width: 650px) {
body {
	width: auto !important;
}
.container {
	width: 95% !important;
	padding-left: 20px !important;
	padding-right: 20px !important;
}
.image-100-percent img {
	width: 100% !important;
	height: auto !important;
	max-width: 100% !important;
}
.full-width {
	width: 100% !important;
}
.text-center {
	text-align: center !important;
}
td[class=3Dremove] {
	display: none !important;
}
}
@media only screen and (max-width: 479px) {
body {
	font-size: 10px !important;
}
.container {
	width: 95% !important;
	padding-left: 10px !important;
	padding-right: 10px !important;
}
.mobiletext {
	font-size: 16px !important;
	line-height: 20px !important;
}
.mobiletitle {
	font-size: 22px !important;
	line-height: 26px !important;
}
.image-100-percent img {
	width: 100% !important;
	height: auto !important;
	max-width: 100% !important;
	min-width: 124px !important;
}
.full-width {
	width: 100% !important;
}
.text-center {
	text-align: center !important;
}
td[class=3Dremove] {
	display: none !important;
}
}
@media only screen and (min-width:768px) {
.templateContainer {
	width: 640px !important;
}
}
</style>
</head>
<body style=3D"padding:0;width:100%;background-color:#f8f8f8;-webkit-text=
-size-adjust:100%;margin:0;-ms-text-size-adjust:100%;">=0D
<div style=3D"color:transparent;visibility:hidden;opacity:0;font-size:0px=
;border:0;max-height:1px;width:1px;margin:0px;padding:0px;border-width:0p=
x!important;display:none!important;line-height:0px!important;"><img borde=
r=3D"0" width=3D"1" height=3D"1" src=3D"https://td.perfect-quotes.com/q/1=
maAQDPyD3rwe0C16cifFA~~/AAAq-QA~/RgRi42u7PVcFc3BjZXVCCmEAu-YAYS4SbuBSD3Rl=
YW1Ab3JpZW50by51a1gEAAAAAA~~" style=3D"text-decoration:none;-ms-interpola=
tion-mode:bicubic;line-height:100%;outline:none;display:block !important;=
border:0;height:auto !important;"></div>=0D

<img src=3D"https://cdn.perfect-quotes.com/px/YWE9MzQ3ODI4Njkmc2VpPTMwNjQ=
wMyZ0az1BZW12Sk94T2ZQZ0FaekQyR3NONCZ0PTEmYz05MGFzODc2ZmQ4OWFzNWZnOGEwOXM=3D=
" style=3D"top:-50px;text-decoration:none;-ms-interpolation-mode:bicubic;=
line-height:100%;outline:none;display:block !important;position:absolute;=
border:0;height:auto !important;" width=3D"1" height=3D"1" border=3D"0"> =
<a href=3D'http://track.adamtest.viaduct.io/wpk1ye/RqY2c7vL' style=3D"tex=
t-decoration:none !important;mso-line-height-rule:exactly;-webkit-text-si=
ze-adjust:100%;-ms-text-size-adjust:100%;"></a>
<center>
  <table align=3D"center" border=3D"0" cellpadding=3D"0" cellspacing=3D"0=
" width=3D"100%" id=3D"bodyTable" style=3D"mso-table-lspace:0;border-spac=
ing:0;padding:0;width:100%;mso-table-rspace:0;-webkit-text-size-adjust:10=
0%;border-collapse:collapse;margin:0;-ms-text-size-adjust:100%;">
    <tr>
      <td align=3D"center" valign=3D"top" id=3D"bodyCell" style=3D"mso-li=
ne-height-rule:exactly;padding:0;width:100%;-webkit-text-size-adjust:100%=
;border-collapse:collapse;margin:0;-ms-text-size-adjust:100%;"><!-- BEGIN=
 TEMPLATE // --> =

        <!--[if (gte mso 9)|(IE)]>
          <table align=3D"center" border=3D"0" cellspacing=3D"0" cellpadd=
ing=3D"0" width=3D"100%" style=3D"width:640px;">
            <tr>
              <td align=3D"center" valign=3D"top" width=3D"100%" style=3D=
"width:640px;">
                <![endif]-->
        =

        <table bgcolor=3D"#ffffff" border=3D"0" cellpadding=3D"0" cellspa=
cing=3D"0" width=3D"640" class=3D"full-width" style=3D"mso-table-lspace:0=
;border-spacing:0;mso-table-rspace:0;-webkit-text-size-adjust:100%;border=
-collapse:collapse;-ms-text-size-adjust:100%;">
          <tr>
            <td style=3D"mso-line-height-rule:exactly;-webkit-text-size-a=
djust:100%;border-collapse:collapse;-ms-text-size-adjust:100%;"><table bo=
rder=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"100%" style=3D"ms=
o-table-lspace:0;border-spacing:0;mso-table-rspace:0;-webkit-text-size-ad=
just:100%;border-collapse:collapse;-ms-text-size-adjust:100%;">
                <tr>
                  <td align=3D"center" bgcolor=3D"#f8f8f8" valign=3D"top"=
 class=3D"fix-box" style=3D"mso-line-height-rule:exactly;-webkit-text-siz=
e-adjust:100%;border-collapse:collapse;-ms-text-size-adjust:100%;"><table=
 width=3D"640" align=3D"center" border=3D"0" cellspacing=3D"0" cellpaddin=
g=3D"0" class=3D"full-width" style=3D"mso-table-lspace:0;border-spacing:0=
;mso-table-rspace:0;-webkit-text-size-adjust:100%;border-collapse:collaps=
e;-ms-text-size-adjust:100%;">
                      <tr>
                        <td align=3D"left" style=3D"word-break:break-word=
;mso-line-height-rule:exactly;-webkit-text-size-adjust:100%;font-size:0px=
;border-collapse:collapse;-ms-text-size-adjust:100%;"><div style=3D"font-=
family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:1;=
text-align:left;color:#000000;">
                            <div style=3D"display:none !important; visibi=
lity:hidden; mso-hide:all; font-size:1px; color:#ffffff; line-height:1px;=
 max-height:0px; max-width:0px; opacity:0;overflow:hidden;">Invest in the=
 UK's best performing asset class</div>
                            <div style=3D"display: none; max-height: 0px;=
 overflow: hidden;">=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=
=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=
=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=C2=
=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=
=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=
=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0 =C2=A0=E2=80=8C=C2=A0=E2=
=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=
=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=
=80=8C=C2=A0=E2=80=8C=C2=A0 =C2=A0=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=
=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=
=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0 =
=C2=A0=C2=A0 =C2=A0=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=
=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=
=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0 =C2=A0=E2=80=8C=
=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=
=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=
=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=
=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=C2=A0=E2=80=8C=
=C2=A0 =C2=A0</div>
                          </div></td>
                      </tr>
                      <tr>
                        <td align=3D"center" style=3D"mso-line-height-rul=
e:exactly;-webkit-text-size-adjust:100%;border-collapse:collapse;-ms-text=
-size-adjust:100%;"><div style=3D"font-family: arial, helvetica, sans-ser=
if; color:#000000; text-align: center; font-size: 11px"><div style=3D"fon=
t-family: arial, helvetica, sans-serif; color:#000000; text-align: center=
; font-size: 11px">
<p style=3D"mso-line-height-rule:exactly;padding:0;-webkit-text-size-adju=
st:100%;margin:0;-ms-text-size-adjust:100%;">ADs | Add <a style=3D"text-d=
ecoration:none !important;mso-line-height-rule:exactly;color:#000000;-web=
kit-text-size-adjust:100%;-ms-text-size-adjust:100%;" href=3D"mailto:mail=
@reply.perfect-quotes.com">Perfect Quotes</a> to your address book | <a s=
tyle=3D"text-decoration:none !important;mso-line-height-rule:exactly;colo=
r:#000000;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;" href=3D=
'http://track.adamtest.viaduct.io/wpk1ye/juFkxpIA' target=3D"_blank">Unsu=
bscribe</a></p>
</div></div></td>
                      </tr>
                    </table></td>
                </tr>
                <tr>
                  <td align=3D"center" valign=3D"top" class=3D"fix-box" s=
tyle=3D"mso-line-height-rule:exactly;-webkit-text-size-adjust:100%;border=
-collapse:collapse;-ms-text-size-adjust:100%;"><table width=3D"640" bgcol=
or=3D"#262f37" align=3D"center" border=3D"0" cellspacing=3D"0" cellpaddin=
g=3D"0" class=3D"full-width" style=3D"mso-table-lspace:0;border-spacing:0=
;mso-table-rspace:0;-webkit-text-size-adjust:100%;border-collapse:collaps=
e;-ms-text-size-adjust:100%;">
                      <tbody>
                        <tr>
                          <td style=3D"mso-line-height-rule:exactly;-webk=
it-text-size-adjust:100%;border-collapse:collapse;-ms-text-size-adjust:10=
0%;"><table align=3D"center" border=3D"0" cellpadding=3D"0" cellspacing=3D=
"0" class=3D"full-width" style=3D"mso-table-lspace:0;border-spacing:0;mso=
-table-rspace:0;-webkit-text-size-adjust:100%;border-collapse:collapse;-m=
s-text-size-adjust:100%;">
                              <tbody>
                                <tr>
                                  <td width=3D"100%" align=3D"center" cla=
ss=3D"image-100-percent" style=3D"mso-line-height-rule:exactly;-webkit-te=
xt-size-adjust:100%;border-collapse:collapse;-ms-text-size-adjust:100%;">=
<a href=3D'http://track.adamtest.viaduct.io/wpk1ye/bqeFd39Y' style=3D"tex=
t-decoration:none !important;mso-line-height-rule:exactly;-webkit-text-si=
ze-adjust:100%;-ms-text-size-adjust:100%;"> <img src=3D"https://cdn.perfe=
ct-quotes.com/cdn/17806/banner.jpg" style=3D"text-decoration:none;-ms-int=
erpolation-mode:bicubic;line-height:100%;outline:none;display:block !impo=
rtant;border:0;height:auto;" alt=3D"The Villas
" class=3D"image-100-percent"> </a></td>
                                </tr>
                              </tbody>
                            </table></td>
                        </tr>
                      </tbody>
                    </table></td>
                </tr>
                <tr>
                  <td align=3D"center" valign=3D"top" class=3D"fix-box" s=
tyle=3D"mso-line-height-rule:exactly;-webkit-text-size-adjust:100%;border=
-collapse:collapse;-ms-text-size-adjust:100%;"><table width=3D"100%" bgco=
lor=3D"#da2d27" align=3D"center" border=3D"0" cellspacing=3D"0" cellpaddi=
ng=3D"0" class=3D"full-width" style=3D"mso-table-lspace:0;border-spacing:=
0;mso-table-rspace:0;-webkit-text-size-adjust:100%;border-collapse:collap=
se;-ms-text-size-adjust:100%;">
                      <tbody>
                        <tr>
                          <td width=3D"15" style=3D"mso-line-height-rule:=
exactly;-webkit-text-size-adjust:100%;border-collapse:collapse;-ms-text-s=
ize-adjust:100%;"></td>
                          <td style=3D"mso-line-height-rule:exactly;paddi=
ng:5px 0px;-webkit-text-size-adjust:100%;border-collapse:collapse;-ms-tex=
t-size-adjust:100%;"><table align=3D"center" cellpadding=3D"0" cellspacin=
g=3D"0" border=3D"0" style=3D"mso-table-lspace:0;border-spacing:0;mso-tab=
le-rspace:0;-webkit-text-size-adjust:100%;border-collapse:collapse;-ms-te=
xt-size-adjust:100%;" width=3D"100%">
                              <tbody>
                                <tr>
                                  <td style=3D"mso-line-height-rule:exact=
ly;-webkit-text-size-adjust:100%;border-collapse:collapse;-ms-text-size-a=
djust:100%;"><table width=3D"610" align=3D"center" class=3D"full-width" c=
ellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"mso-table-lspace=
:0;border-spacing:0;mso-table-rspace:0;-webkit-text-size-adjust:100%;bord=
er-collapse:collapse;-ms-text-size-adjust:100%;">
                                      <tr>
                                        <td style=3D"mso-line-height-rule=
:exactly;-webkit-text-size-adjust:100%;border-collapse:collapse;-ms-text-=
size-adjust:100%;"><table align=3D"left" border=3D"0" cellpadding=3D"0" c=
ellspacing=3D"0" class=3D"full-width" style=3D"mso-table-lspace:0;border-=
spacing:0;mso-table-rspace:0;-webkit-text-size-adjust:100%;border-collaps=
e:collapse;-ms-text-size-adjust:100%;">
                                            <tbody>
                                              <tr>
                                                <td style=3D"mso-line-hei=
ght-rule:exactly;padding:0px 0px;-webkit-text-size-adjust:100%;border-col=
lapse:collapse;-ms-text-size-adjust:100%;"><table align=3D"center" cellpa=
dding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"mso-table-lspace:0;bo=
rder-spacing:0;mso-table-rspace:0;-webkit-text-size-adjust:100%;border-co=
llapse:collapse;-ms-text-size-adjust:100%;" class=3D"full-width">
                                                    <tr>
                                                      <td valign=3D"middl=
e" width=3D"100%" align=3D"center" style=3D"font-family:'Poppins', Arial,=
 Helvetica, sans-serif;line-height:35px;mso-line-height-rule:exactly;padd=
ing:3px 5px  0px;color:#ffffff;text-align:left;text-transform:uppercase;-=
webkit-text-size-adjust:100%;font-weight:900;font-size:30px;border-collap=
se:collapse;-ms-text-size-adjust:100%;"> Phase 2 Now Released! </td>
                                                    </tr>
                                                  </table></td>
                                              </tr>
                                            </tbody>
                                          </table></td>
                                      </tr>
                                    </table></td>
                                </tr>
                              </tbody>
                            </table></td>
                          <td width=3D"15" style=3D"mso-line-height-rule:=
exactly;-webkit-text-size-adjust:100%;border-collapse:collapse;-ms-text-s=
ize-adjust:100%;"></td>
                        </tr>
                      </tbody>
                    </table></td>
                </tr>
                <tr>
                  <td align=3D"center" valign=3D"top" class=3D"fix-box" s=
tyle=3D"mso-line-height-rule:exactly;-webkit-text-size-adjust:100%;border=
-collapse:collapse;-ms-text-size-adjust:100%;"><table width=3D"100%" bgco=
lor=3D"#2c2c2c" align=3D"center" border=3D"0" cellspacing=3D"0" cellpaddi=
ng=3D"0" class=3D"full-width" style=3D"mso-table-lspace:0;border-spacing:=
0;mso-table-rspace:0;-webkit-text-size-adjust:100%;border-collapse:collap=
se;-ms-text-size-adjust:100%;">
                      <tbody>
                        <tr>
                          <td width=3D"15" style=3D"mso-line-height-rule:=
exactly;-webkit-text-size-adjust:100%;border-collapse:collapse;-ms-text-s=
ize-adjust:100%;"></td>
                          <td style=3D"mso-line-height-rule:exactly;paddi=
ng:5px 0px;-webkit-text-size-adjust:100%;border-collapse:collapse;-ms-tex=
t-size-adjust:100%;"><table align=3D"center" cellpadding=3D"0" cellspacin=
g=3D"0" border=3D"0" style=3D"mso-table-lspace:0;border-spacing:0;mso-tab=
le-rspace:0;-webkit-text-size-adjust:100%;border-collapse:collapse;-ms-te=
xt-size-adjust:100%;" width=3D"100%">
                              <tbody>
                                <tr>
                                  <td style=3D"mso-line-height-rule:exact=
ly;-webkit-text-size-adjust:100%;border-collapse:collapse;-ms-text-size-a=
djust:100%;"><table width=3D"610" align=3D"center" class=3D"full-width" c=
ellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"mso-table-lspace=
:0;border-spacing:0;mso-table-rspace:0;-webkit-text-size-adjust:100%;bord=
er-collapse:collapse;-ms-text-size-adjust:100%;">
                                      <tr>
                                        <td style=3D"mso-line-height-rule=
:exactly;-webkit-text-size-adjust:100%;border-collapse:collapse;-ms-text-=
size-adjust:100%;"><table align=3D"left" border=3D"0" cellpadding=3D"0" c=
ellspacing=3D"0" class=3D"full-width" style=3D"mso-table-lspace:0;border-=
spacing:0;mso-table-rspace:0;-webkit-text-size-adjust:100%;border-collaps=
e:collapse;-ms-text-size-adjust:100%;">
                                            <tbody>
                                              <tr>
                                                <td style=3D"mso-line-hei=
ght-rule:exactly;padding:0px 0px;-webkit-text-size-adjust:100%;border-col=
lapse:collapse;-ms-text-size-adjust:100%;"><table align=3D"center" cellpa=
dding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"mso-table-lspace:0;bo=
rder-spacing:0;mso-table-rspace:0;-webkit-text-size-adjust:100%;border-co=
llapse:collapse;-ms-text-size-adjust:100%;" class=3D"full-width">
                                                    <tr>
                                                      <td valign=3D"middl=
e" width=3D"100%" align=3D"center" style=3D"font-family:'Poppins', Arial,=
 Helvetica, sans-serif;line-height:30px;mso-line-height-rule:exactly;padd=
ing:6px 5px;color:#ffffff;text-align:left;text-transform:uppercase;-webki=
t-text-size-adjust:100%;font-weight:600;font-size:22px;border-collapse:co=
llapse;-ms-text-size-adjust:100%;"> 8.5% NET Returns Guaranteed For 3 Yea=
rs </td>
                                                    </tr>
                                                  </table></td>
                                              </tr>
                                            </tbody>
                                          </table></td>
                                      </tr>
                                    </table></td>
                                </tr>
                              </tbody>
                            </table></td>
                          <td width=3D"15" style=3D"mso-line-height-rule:=
exactly;-webkit-text-size-adjust:100%;border-collapse:collapse;-ms-text-s=
ize-adjust:100%;"></td>
                        </tr>
                      </tbody>
                    </table></td>
                </tr>
                <tr>
                  <td align=3D"center" valign=3D"top" class=3D"fix-box" s=
tyle=3D"mso-line-height-rule:exactly;-webkit-text-size-adjust:100%;border=
-collapse:collapse;-ms-text-size-adjust:100%;"><table width=3D"640" bgcol=
or=3D"#ffffff" align=3D"center" border=3D"0" cellspacing=3D"0" cellpaddin=
g=3D"0" class=3D"full-width" style=3D"mso-table-lspace:0;border-spacing:0=
;mso-table-rspace:0;-webkit-text-size-adjust:100%;border-collapse:collaps=
e;-ms-text-size-adjust:100%;">
                      <tr>
                        <td width=3D"25" style=3D"mso-line-height-rule:ex=
actly;-webkit-text-size-adjust:100%;border-collapse:collapse;-ms-text-siz=
e-adjust:100%;"></td>
                        <td style=3D"mso-line-height-rule:exactly;-webkit=
-text-size-adjust:100%;border-collapse:collapse;-ms-text-size-adjust:100%=
;"><table class=3D"full-width" border=3D"0" cellspacing=3D"0" width=3D"10=
0%" cellpadding=3D"0" align=3D"center" style=3D"mso-table-lspace:0;border=
-spacing:0;mso-table-rspace:0;-webkit-text-size-adjust:100%;border-collap=
se:collapse;-ms-text-size-adjust:100%;">
                            <tr>
                              <td valign=3D"top" style=3D"mso-line-height=
-rule:exactly;-webkit-text-size-adjust:100%;border-collapse:collapse;-ms-=
text-size-adjust:100%;"><table align=3D"center" cellpadding=3D"0" cellspa=
cing=3D"0" border=3D"0" style=3D"mso-table-lspace:0;border-spacing:0;mso-=
table-rspace:0;-webkit-text-size-adjust:100%;border-collapse:collapse;-ms=
-text-size-adjust:100%;" class=3D"full-width">
                                  <tr>
                                    <td width=3D"100%" align=3D"center" s=
tyle=3D"font-family:'Poppins', Arial, Helvetica, sans-serif;mso-line-heig=
ht-rule:exactly;line-height:24px;padding:25px 10px 15px;color:#000000;tex=
t-align:center;-webkit-text-size-adjust:100%;font-weight:400;font-size:16=
px;border-collapse:collapse;-ms-text-size-adjust:100%;">The Villas is a b=
rand-new investment opportunity in the student accommodation sector, idea=
lly located in Stoke-on-Trent to meet the huge demand from the 25,000+ st=
udents at the city=E2=80=99s Keele and Staffordshire Universities. The 17=
4 studio apartments offer spacious, contemporary interiors, with developm=
ent facilities including communal study and relaxation spaces, caf=C3=A9,=
 gym, bike storage and car parks. Units start from a low =C2=A374,950, wi=
th furniture included within the price and 8.5% NET returns guaranteed fo=
r the first 3 years. </td>
                                  </tr>
                                </table></td>
                            </tr>
                          </table></td>
                        <td width=3D"25" style=3D"mso-line-height-rule:ex=
actly;-webkit-text-size-adjust:100%;border-collapse:collapse;-ms-text-siz=
e-adjust:100%;"></td>
                      </tr>
                    </table></td>
                </tr>
                <tr>
                  <td align=3D"center" valign=3D"top" style=3D"mso-line-h=
eight-rule:exactly;padding:10px 0px 10px;-webkit-text-size-adjust:100%;bo=
rder-collapse:collapse;-ms-text-size-adjust:100%;" class=3D"fix-box"><tab=
le bgcolor=3D"#ffffff" width=3D"640" align=3D"center" border=3D"0" cellsp=
acing=3D"0" cellpadding=3D"0" class=3D"full-width" style=3D"mso-table-lsp=
ace:0;border-spacing:0;mso-table-rspace:0;-webkit-text-size-adjust:100%;b=
order-collapse:collapse;-ms-text-size-adjust:100%;">
                      <tr>
                        <td width=3D"30" style=3D"mso-line-height-rule:ex=
actly;-webkit-text-size-adjust:100%;border-collapse:collapse;-ms-text-siz=
e-adjust:100%;"></td>
                        <td bgcolor=3D"#da2d27" style=3D"mso-line-height-=
rule:exactly;padding:0px;-webkit-text-size-adjust:100%;border-collapse:co=
llapse;-ms-text-size-adjust:100%;"><table bgcolor=3D"#da2d27" class=3D"fu=
ll-width" border=3D"0" cellspacing=3D"0" cellpadding=3D"0" align=3D"cente=
r" style=3D"mso-table-lspace:0;border-spacing:0;mso-table-rspace:0;-webki=
t-text-size-adjust:100%;border-collapse:collapse;-ms-text-size-adjust:100=
%;">
                            <tr>
                              <td style=3D"mso-line-height-rule:exactly;p=
adding:5px 10px;-webkit-text-size-adjust:100%;border-collapse:collapse;-m=
s-text-size-adjust:100%;" align=3D"right" valign=3D"top"><a href=3D'http:=
//track.adamtest.viaduct.io/wpk1ye/kWwMAIGR' style=3D"text-decoration:non=
e !important;mso-line-height-rule:exactly;-webkit-text-size-adjust:100%;-=
ms-text-size-adjust:100%;"><img width=3D"106" src=3D"https://cdn.perfect-=
quotes.com/cdn/17806/percentlogo.png" style=3D"text-decoration:none;-ms-i=
nterpolation-mode:bicubic;max-width:106px;line-height:100%;outline:none;d=
isplay:block !important;border:0;height:auto;"></a></td>
                              <td width=3D"100%" align=3D"center" style=3D=
"font-family:'Poppins', Arial, Helvetica, sans-serif;line-height:28px;mso=
-line-height-rule:exactly;color:#ffffff;text-align:centre;padding:6px 5px=
 4px 5px;text-transform:uppercase;-webkit-text-size-adjust:100%;font-weig=
ht:500;font-size:22px;border-collapse:collapse;-ms-text-size-adjust:100%;=
">The Villas is a Cash-Only Investor Opportunity From Birchmore </td>
                            </tr>
                          </table></td>
                        <td width=3D"30" style=3D"mso-line-height-rule:ex=
actly;-webkit-text-size-adjust:100%;border-collapse:collapse;-ms-text-siz=
e-adjust:100%;"></td>
                      </tr>
                    </table></td>
                </tr>
                <tr>
                  <td align=3D"center" valign=3D"top" style=3D"mso-line-h=
eight-rule:exactly;padding:20px 0px 10px;-webkit-text-size-adjust:100%;bo=
rder-collapse:collapse;-ms-text-size-adjust:100%;" class=3D"fix-box"><tab=
le bgcolor=3D"#ffffff" width=3D"640" align=3D"center" border=3D"0" cellsp=
acing=3D"0" cellpadding=3D"0" class=3D"full-width" style=3D"mso-table-lsp=
ace:0;border-spacing:0;mso-table-rspace:0;-webkit-text-size-adjust:100%;b=
order-collapse:collapse;-ms-text-size-adjust:100%;">
                      <tr>
                        <td width=3D"30" style=3D"mso-line-height-rule:ex=
actly;-webkit-text-size-adjust:100%;border-collapse:collapse;-ms-text-siz=
e-adjust:100%;"></td>
                        <td style=3D"mso-line-height-rule:exactly;padding=
:0px;-webkit-text-size-adjust:100%;border-collapse:collapse;-ms-text-size=
-adjust:100%;"><table style=3D"mso-table-lspace:0;border-spacing:0;border=
-bottom:25px solid #ffffff;mso-table-rspace:0;-webkit-text-size-adjust:10=
0%;border-collapse:collapse;-ms-text-size-adjust:100%;" bgcolor=3D"#f6f6f=
6" class=3D"full-width" border=3D"0" cellspacing=3D"0" width=3D"275" cell=
padding=3D"0" align=3D"left">
                            <tr>
                              <td colspan=3D"3" align=3D"center" valign=3D=
"top" style=3D"mso-line-height-rule:exactly;-webkit-text-size-adjust:100%=
;border-collapse:collapse;-ms-text-size-adjust:100%;"><a href=3D'http://t=
rack.adamtest.viaduct.io/wpk1ye/NrOxRevH' style=3D"text-decoration:none !=
important;mso-line-height-rule:exactly;-webkit-text-size-adjust:100%;-ms-=
text-size-adjust:100%;"><img width=3D"120" src=3D"https://cdn.perfect-quo=
tes.com/cdn/17806/icon1.png" style=3D"text-decoration:none;-ms-interpolat=
ion-mode:bicubic;max-width:120px;line-height:100%;outline:none;display:bl=
ock !important;border:0;height:auto;"></a></td>
                            </tr>
                            <tr>
                              <td valign=3D"top" style=3D"mso-line-height=
-rule:exactly;-webkit-text-size-adjust:100%;border-collapse:collapse;-ms-=
text-size-adjust:100%;"><table width=3D"100%" align=3D"center" cellpaddin=
g=3D"0" cellspacing=3D"0" border=3D"0" style=3D"mso-table-lspace:0;border=
-spacing:0;mso-table-rspace:0;-webkit-text-size-adjust:100%;border-collap=
se:collapse;-ms-text-size-adjust:100%;" class=3D"full-width">
                                  <tr>
                                    <td width=3D"100%" align=3D"center" s=
tyle=3D"font-family:'Poppins', Arial, Helvetica, sans-serif;line-height:2=
4px;mso-line-height-rule:exactly;padding:5px 5px 0px;color:#2c2c2c;text-a=
lign:center;text-transform:uppercase;-webkit-text-size-adjust:100%;font-w=
eight:600;font-size:20px;border-collapse:collapse;-ms-text-size-adjust:10=
0%;">City-Centre Location </td>
                                  </tr>
                                  <tr>
                                    <td width=3D"100%" align=3D"center" s=
tyle=3D"font-family:'Poppins', Arial, Helvetica, sans-serif;line-height:2=
0px;mso-line-height-rule:exactly;color:#2c2c2c;padding:5px 10px  15px;tex=
t-align:center;border-bottom:5px solid #2c2c2c;-webkit-text-size-adjust:1=
00%;font-weight:400;font-size:15px;border-collapse:collapse;-ms-text-size=
-adjust:100%;"> Perfectly situated in the<br style=3D"line-height:100%;">=

                                      centre of Stoke-on-Trent,<br style=3D=
"line-height:100%;">
                                      ensuring maximum appeal to<br style=
=3D"line-height:100%;">
                                      the city=E2=80=99s student populati=
on </td>
                                  </tr>
                                </table></td>
                            </tr>
                          </table>
                          <table style=3D"mso-table-lspace:0;border-spaci=
ng:0;border-bottom:25px solid #ffffff;mso-table-rspace:0;-webkit-text-siz=
e-adjust:100%;border-collapse:collapse;-ms-text-size-adjust:100%;" bgcolo=
r=3D"#f6f6f6" class=3D"full-width" border=3D"0" cellspacing=3D"0" width=3D=
"275" cellpadding=3D"0" align=3D"right">
                            <tr>
                              <td colspan=3D"3" align=3D"center" valign=3D=
"top" style=3D"mso-line-height-rule:exactly;-webkit-text-size-adjust:100%=
;border-collapse:collapse;-ms-text-size-adjust:100%;"><a href=3D'http://t=
rack.adamtest.viaduct.io/wpk1ye/Kah6eGaJ' style=3D"text-decoration:none !=
important;mso-line-height-rule:exactly;-webkit-text-size-adjust:100%;-ms-=
text-size-adjust:100%;"><img width=3D"120" src=3D"https://cdn.perfect-quo=
tes.com/cdn/17806/icon4.png" style=3D"text-decoration:none;-ms-interpolat=
ion-mode:bicubic;max-width:120px;line-height:100%;outline:none;display:bl=
ock !important;border:0;height:auto;"></a></td>
                            </tr>
                            <tr>
                              <td valign=3D"top" style=3D"mso-line-height=
-rule:exactly;-webkit-text-size-adjust:100%;border-collapse:collapse;-ms-=
text-size-adjust:100%;"><table align=3D"center" cellpadding=3D"0" cellspa=
cing=3D"0" border=3D"0" style=3D"mso-table-lspace:0;border-spacing:0;mso-=
table-rspace:0;-webkit-text-size-adjust:100%;border-collapse:collapse;-ms=
-text-size-adjust:100%;" class=3D"full-width">
                                  <tr>
                                    <td width=3D"100%" align=3D"center" s=
tyle=3D"font-family:'Poppins', Arial, Helvetica, sans-serif;mso-line-heig=
ht-rule:exactly;line-height:24px;color:#2c2c2c;text-align:center;padding:=
5px 5px 0px;text-transform:uppercase;-webkit-text-size-adjust:100%;font-w=
eight:600;font-size:20px;border-collapse:collapse;-ms-text-size-adjust:10=
0%;">Hands-Off Investment </td>
                                  </tr>
                                  <tr>
                                    <td width=3D"100%" align=3D"center" s=
tyle=3D"font-family:'Poppins', Arial, Helvetica, sans-serif;line-height:2=
0px;mso-line-height-rule:exactly;color:#2c2c2c;padding:5px 10px  15px;tex=
t-align:center;border-bottom:5px solid #2c2c2c;-webkit-text-size-adjust:1=
00%;font-weight:400;font-size:15px;border-collapse:collapse;-ms-text-size=
-adjust:100%;"> Fully managed by Homes<br style=3D"line-height:100%;">
                                      For Students, one of the UK=E2=80=99=
s<br style=3D"line-height:100%;">
                                      leading providers of quality<br sty=
le=3D"line-height:100%;">
                                      student accommodation </td>
                                  </tr>
                                </table></td>
                            </tr>
                          </table></td>
                        <td width=3D"30" style=3D"mso-line-height-rule:ex=
actly;-webkit-text-size-adjust:100%;border-collapse:collapse;-ms-text-siz=
e-adjust:100%;"></td>
                      </tr>
                      <tr>
                        <td width=3D"30" style=3D"mso-line-height-rule:ex=
actly;-webkit-text-size-adjust:100%;border-collapse:collapse;-ms-text-siz=
e-adjust:100%;"></td>
                        <td style=3D"mso-line-height-rule:exactly;padding=
:0px;-webkit-text-size-adjust:100%;border-collapse:collapse;-ms-text-size=
-adjust:100%;"><table style=3D"mso-table-lspace:0;border-spacing:0;border=
-bottom:10px solid #ffffff;mso-table-rspace:0;-webkit-text-size-adjust:10=
0%;border-collapse:collapse;-ms-text-size-adjust:100%;" bgcolor=3D"#f6f6f=
6" class=3D"full-width" border=3D"0" cellspacing=3D"0" width=3D"275" cell=
padding=3D"0" align=3D"left">
                            <tr>
                              <td colspan=3D"3" align=3D"center" valign=3D=
"top" style=3D"mso-line-height-rule:exactly;-webkit-text-size-adjust:100%=
;border-collapse:collapse;-ms-text-size-adjust:100%;"><a href=3D'http://t=
rack.adamtest.viaduct.io/wpk1ye/alRllU9d' style=3D"text-decoration:none !=
important;mso-line-height-rule:exactly;-webkit-text-size-adjust:100%;-ms-=
text-size-adjust:100%;"><img width=3D"120" src=3D"https://cdn.perfect-quo=
tes.com/cdn/17806/icon3.png" style=3D"text-decoration:none;-ms-interpolat=
ion-mode:bicubic;max-width:120px;line-height:100%;outline:none;display:bl=
ock !important;border:0;height:auto;"></a></td>
                            </tr>
                            <tr>
                              <td valign=3D"top" style=3D"mso-line-height=
-rule:exactly;-webkit-text-size-adjust:100%;border-collapse:collapse;-ms-=
text-size-adjust:100%;"><table width=3D"100%" align=3D"center" cellpaddin=
g=3D"0" cellspacing=3D"0" border=3D"0" style=3D"mso-table-lspace:0;border=
-spacing:0;mso-table-rspace:0;-webkit-text-size-adjust:100%;border-collap=
se:collapse;-ms-text-size-adjust:100%;" class=3D"full-width">
                                  <tr>
                                    <td width=3D"100%" align=3D"center" s=
tyle=3D"font-family:'Poppins', Arial, Helvetica, sans-serif;line-height:2=
4px;mso-line-height-rule:exactly;color:#2c2c2c;text-align:center;padding:=
5px 5px 0px;text-transform:uppercase;-webkit-text-size-adjust:100%;font-w=
eight:600;font-size:20px;border-collapse:collapse;-ms-text-size-adjust:10=
0%;">FURNITURE INCLUDED </td>
                                  </tr>
                                  <tr>
                                    <td width=3D"100%" align=3D"center" s=
tyle=3D"font-family:'Poppins', Arial, Helvetica, sans-serif;line-height:2=
0px;mso-line-height-rule:exactly;text-align:center;color:#2c2c2c;padding:=
5px 10px  15px;border-bottom:5px solid #2c2c2c;-webkit-text-size-adjust:1=
00%;font-weight:400;font-size:15px;border-collapse:collapse;-ms-text-size=
-adjust:100%;"> Full furniture packs included<br style=3D"line-height:100=
%;">
                                      in the purchase price,<br style=3D"=
line-height:100%;">
                                      providing both value and<br style=3D=
"line-height:100%;">
                                      convenience for investors </td>
                                  </tr>
                                </table></td>
                            </tr>
                          </table>
                          <table style=3D"mso-table-lspace:0;border-spaci=
ng:0;border-bottom:10px solid #ffffff;mso-table-rspace:0;-webkit-text-siz=
e-adjust:100%;border-collapse:collapse;-ms-text-size-adjust:100%;" bgcolo=
r=3D"#f6f6f6" class=3D"full-width" border=3D"0" cellspacing=3D"0" width=3D=
"275" cellpadding=3D"0" align=3D"right">
                            <tr>
                              <td colspan=3D"3" align=3D"center" valign=3D=
"top" style=3D"mso-line-height-rule:exactly;-webkit-text-size-adjust:100%=
;border-collapse:collapse;-ms-text-size-adjust:100%;"><a href=3D'http://t=
rack.adamtest.viaduct.io/wpk1ye/Az715kpB' style=3D"text-decoration:none !=
important;mso-line-height-rule:exactly;-webkit-text-size-adjust:100%;-ms-=
text-size-adjust:100%;"><img width=3D"120" src=3D"https://cdn.perfect-quo=
tes.com/cdn/17806/icon2.png" style=3D"text-decoration:none;-ms-interpolat=
ion-mode:bicubic;max-width:120px;line-height:100%;outline:none;display:bl=
ock !important;border:0;height:auto;"></a></td>
                            </tr>
                            <tr>
                              <td valign=3D"top" style=3D"mso-line-height=
-rule:exactly;-webkit-text-size-adjust:100%;border-collapse:collapse;-ms-=
text-size-adjust:100%;"><table width=3D"100%" align=3D"center" cellpaddin=
g=3D"0" cellspacing=3D"0" border=3D"0" style=3D"mso-table-lspace:0;border=
-spacing:0;mso-table-rspace:0;-webkit-text-size-adjust:100%;border-collap=
se:collapse;-ms-text-size-adjust:100%;" class=3D"full-width">
                                  <tr>
                                    <td width=3D"100%" align=3D"center" s=
tyle=3D"font-family:'Poppins', Arial, Helvetica, sans-serif;mso-line-heig=
ht-rule:exactly;line-height:24px;text-align:center;padding:5px 5px 0px;co=
lor:#2c2c2c;text-transform:uppercase;-webkit-text-size-adjust:100%;font-w=
eight:600;font-size:20px;border-collapse:collapse;-ms-text-size-adjust:10=
0%;">4% Paid On Deposits </td>
                                  </tr>
                                  <tr>
                                    <td width=3D"100%" align=3D"center" s=
tyle=3D"font-family:'Poppins', Arial, Helvetica, sans-serif;line-height:2=
0px;mso-line-height-rule:exactly;padding:5px 10px  15px;text-align:center=
;color:#2c2c2c;border-bottom:5px solid #2c2c2c;-webkit-text-size-adjust:1=
00%;font-weight:400;font-size:15px;border-collapse:collapse;-ms-text-size=
-adjust:100%;"> Interest paid on reservation<br style=3D"line-height:100%=
;">
                                      deposits from exchange until<br sty=
le=3D"line-height:100%;">
                                      the development completes<br style=3D=
"line-height:100%;">
                                      in September 2022 </td>
                                  </tr>
                                </table></td>
                            </tr>
                          </table></td>
                        <td width=3D"30" style=3D"mso-line-height-rule:ex=
actly;-webkit-text-size-adjust:100%;border-collapse:collapse;-ms-text-siz=
e-adjust:100%;"></td>
                      </tr>
                    </table></td>
                </tr>
                <tr>
                  <td align=3D"center" valign=3D"top" class=3D"fix-box" s=
tyle=3D"mso-line-height-rule:exactly;padding-top:15px;-webkit-text-size-a=
djust:100%;border-collapse:collapse;-ms-text-size-adjust:100%;"><table wi=
dth=3D"100%" bgcolor=3D"#2c2c2c" align=3D"center" border=3D"0" cellspacin=
g=3D"0" cellpadding=3D"0" class=3D"full-width" style=3D"mso-table-lspace:=
0;border-spacing:0;border-top:40px solid #1f2738;border-bottom:40px solid=
 #1f2738;mso-table-rspace:0;-webkit-text-size-adjust:100%;border-collapse=
:collapse;-ms-text-size-adjust:100%;">
                      <tbody>
                        <tr>
                          <td bgcolor=3D"#da2d27" width=3D"15" style=3D"m=
so-line-height-rule:exactly;-webkit-text-size-adjust:100%;border-collapse=
:collapse;-ms-text-size-adjust:100%;"></td>
                          <td bgcolor=3D"#da2d27" style=3D"mso-line-heigh=
t-rule:exactly;padding:10px 0px;-webkit-text-size-adjust:100%;border-coll=
apse:collapse;-ms-text-size-adjust:100%;"><table align=3D"center" cellpad=
ding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"mso-table-lspace:0;bor=
der-spacing:0;mso-table-rspace:0;-webkit-text-size-adjust:100%;border-col=
lapse:collapse;-ms-text-size-adjust:100%;" width=3D"100%">
                              <tbody>
                                <tr>
                                  <td style=3D"mso-line-height-rule:exact=
ly;-webkit-text-size-adjust:100%;border-collapse:collapse;-ms-text-size-a=
djust:100%;"><table align=3D"center" cellpadding=3D"0" cellspacing=3D"0" =
border=3D"0" style=3D"mso-table-lspace:0;border-spacing:0;mso-table-rspac=
e:0;-webkit-text-size-adjust:100%;border-collapse:collapse;-ms-text-size-=
adjust:100%;" class=3D"full-width">
                                      <tr>
                                        <td valign=3D"middle" width=3D"10=
0%" align=3D"center" style=3D"font-family:'Poppins', Arial, Helvetica, sa=
ns-serif;line-height:40px;mso-line-height-rule:exactly;text-align:center;=
color:#ffffff;padding:5px 5px  4px;text-transform:uppercase;-webkit-text-=
size-adjust:100%;font-weight:900;font-size:32px;border-collapse:collapse;=
-ms-text-size-adjust:100%;"><a style=3D"text-decoration:none;mso-line-hei=
ght-rule:exactly;color:#ffffff;-webkit-text-size-adjust:100%;-ms-text-siz=
e-adjust:100%;" href=3D'http://track.adamtest.viaduct.io/wpk1ye/x9ladWLR'=
>REQUEST YOUR BROCHURE</a></td>
                                      </tr>
                                    </table></td>
                                </tr>
                              </tbody>
                            </table></td>
                          <td width=3D"15" bgcolor=3D"#da2d27" style=3D"m=
so-line-height-rule:exactly;-webkit-text-size-adjust:100%;border-collapse=
:collapse;-ms-text-size-adjust:100%;"></td>
                        </tr>
                      </tbody>
                    </table></td>
                </tr>
              </table></td>
          </tr>
        </table>
        =

        <!--[if (gte mso 9)|(IE)]>
          </td>
        </tr>
      </table>
      <![endif]--> =

        =

        <!-- // END TEMPLATE --> =

        =

        <!--[if (gte mso 9)|(IE)]>
          <table align=3D"center" border=3D"0" cellspacing=3D"0" cellpadd=
ing=3D"0" width=3D"100%" style=3D"width:640px;">
            <tr>
              <td align=3D"center" valign=3D"top" width=3D"100%" style=3D=
"width:640px;">
                <![endif]-->
        =

        <table border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"=
640" class=3D"full-width" style=3D"mso-table-lspace:0;border-spacing:0;ms=
o-table-rspace:0;-webkit-text-size-adjust:100%;border-collapse:collapse;-=
ms-text-size-adjust:100%;">
          <tr>
            <td align=3D"center" style=3D"mso-line-height-rule:exactly;-w=
ebkit-text-size-adjust:100%;border-collapse:collapse;-ms-text-size-adjust=
:100%;"><div style=3D"font-family:Arial, Helvetica, sans-serif; font-size=
:10px; color:#000000; line-height:20px; text-align: center"><tr><td align=
=3D"center" style=3D"mso-line-height-rule:exactly;-webkit-text-size-adjus=
t:100%;border-collapse:collapse;-ms-text-size-adjust:100%;">=0D
<div style=3D"font-family:Arial, Helvetica, sans-serif; font-size:10px; c=
olor:#000000; line-height:20px; text-align: center">=0D
<span><br style=3D"line-height:100%;">You are receiving message 34782869 =
on your email address from DataSoftSolutions LP, 64 Cumberland Street, Ed=
inburgh, UK<br style=3D"line-height:100%;">=0D
because you are on Time Travel Promotion LP's list of managers and profes=
sionals under controller ID AemvJOxOfPgAZzD2GsN4.<br style=3D"line-height=
:100%;">=0D
You have the right of access, rectification, opposition and consent for y=
our data which you can access under <a href=3D'http://track.adamtest.viad=
uct.io/wpk1ye/ivU9lF3O' style=3D"text-decoration:underline;mso-line-heigh=
t-rule:exactly;color:#000000;-webkit-text-size-adjust:100%;-ms-text-size-=
adjust:100%;">Privacy policy.</a><br style=3D"line-height:100%;">=0D
To stop receiving Special Offers by email for your professional activity<=
br style=3D"line-height:100%;">=0D
or if you wish to personalize your experience follow the data controller =
<a href=3D'http://track.adamtest.viaduct.io/wpk1ye/So0hAySC' style=3D"tex=
t-decoration:underline;mso-line-height-rule:exactly;color:#000000;-webkit=
-text-size-adjust:100%;-ms-text-size-adjust:100%;">page</a>.=0D
</span></div>=0D
</td></tr></div></td>
          </tr>
        </table>
        =

        <!--[if (gte mso 9)|(IE)]>
          </td>
        </tr>
      </table>
      <![endif]--></td>
    </tr>
  </table>
</center>
<img src=3D"https://cdn.perfect-quotes.com/timg/aHR0cHM6Ly9hZGxlYWRybmV0d=
29yay5jb20vaS5hc2h4P2E9MTAmYz0xNTgzJnMxPVNVQl9JRA=3D=3D" width=3D"1" heig=
ht=3D"1" border=3D"0" style=3D"text-decoration:none;-ms-interpolation-mod=
e:bicubic;line-height:100%;outline:none;display:block !important;border:0=
;height:auto !important;">
=0D
<img border=3D"0" width=3D"1" height=3D"1" alt=3D"" src=3D"https://td.per=
fect-quotes.com/q/dUoNiFL_C9xh7FaMg4YN0w~~/AAAq-QA~/RgRi42u7PlcFc3BjZXVCC=
mEAu-YAYS4SbuBSD3RlYW1Ab3JpZW50by51a1gEAAAAAA~~" style=3D"text-decoration=
:none;-ms-interpolation-mode:bicubic;line-height:100%;outline:none;displa=
y:block !important;border:0;height:auto !important;">=0D
<p class=3D'ampimg' style=3D'display:none;visibility:none;margin:0;paddin=
g:0;line-height:0;'><img src=3D'http://track.adamtest.viaduct.io/img/wpk1=
ye/YzFrlleYgzEO' alt=3D''></p></body>
</html>=0D
=0D
