# frozen_string_literal: true

module Postal
  module MessageDB
    module Dialects
      #
      # The contract for a message database dialect.
      #
      # A dialect encapsulates everything that differs between database engines
      # so that the rest of Postal::MessageDB (Database, Provisioner,
      # Statistics, LiveStats) can stay engine-agnostic. Adding an engine means
      # implementing this class, registering it in the Registry and providing a
      # test container.
      #
      # A "namespace" is the unit of isolation for a server's message data: a
      # database on MySQL/MariaDB and a schema on PostgreSQL.
      #
      class Base

        # The identifier used by message_db.adapter to select this dialect.
        def name
          raise NotImplementedError
        end

        # Whether the dialect is complete and safe to run in production. The
        # registry only hands out dialects which report true.
        def available?
          false
        end

        #
        # Identifiers and literals
        #

        # Quote a table or column identifier for this engine.
        def quote_identifier(identifier)
          raise NotImplementedError
        end

        # Escape a string for use as a SQL literal, including the surrounding
        # quotes (for example "'abc'").
        def escape(connection, value)
          raise NotImplementedError
        end

        # The SQL literal for a boolean value.
        def boolean(value)
          value ? "1" : "0"
        end

        #
        # Query execution and errors
        #

        # Run a statement on the connection and return the result.
        def execute(connection, query)
          raise NotImplementedError
        end

        # Whether slow queries should be explained and logged.
        def explain?
          false
        end

        # Log an EXPLAIN for a slow query. Only called when explain? is true.
        def log_explain(connection, query, time, logger)
          nil
        end

        # The exception class raised by the underlying driver. Used to detect
        # engine-specific errors (for example a missing table).
        def error_class
          StandardError
        end

        #
        # Results
        #

        # The id generated by the previous INSERT on the connection.
        def last_insert_id(connection)
          raise NotImplementedError
        end

        # The number of rows affected by the previous statement, given the
        # connection and the result returned by #execute.
        def affected_rows(connection, result)
          raise NotImplementedError
        end

        # The clause appended to an INSERT so the generated id can be read back.
        # Empty when the engine reports it through last_insert_id instead.
        def returning_clause(_table)
          ""
        end

        # The id generated by an INSERT, given the connection and its result.
        def inserted_id(connection, result)
          last_insert_id(connection)
        end

        #
        # Upserts and expressions
        #

        # Build the clause appended to an INSERT which turns it into an upsert,
        # from the columns which identify an existing row and an ordered list of
        # [column, expression] assignments.
        def upsert(conflict_columns, assignments)
          raise NotImplementedError
        end

        # A reference to a column of `table`, used inside upsert expressions.
        # Engines which need it qualified (PostgreSQL, where an unqualified
        # column is ambiguous between the target row and `excluded`) override
        # this.
        def column_reference(_table, column)
          quote_identifier(column)
        end

        # An expression which yields reset_value when `column` is older than
        # `threshold`, and otherwise the existing `counter` plus 1. Used by the
        # live stats rollover.
        def conditional_reset_or_increment(_table, column, threshold, counter, reset_value = 1)
          raise NotImplementedError
        end

        #
        # Connections
        #

        # Build a database connection from the message_db configuration.
        def connect(config)
          raise NotImplementedError
        end

        # Make sure the namespace for a server is available on this connection.
        # Engines whose namespaces are objects on the server (MySQL databases,
        # PostgreSQL schemas) do nothing; SQLite attaches the server's file.
        def ensure_namespace(_connection, _namespace)
        end

        # Called before a namespace is created and after it is removed, so
        # engines whose namespaces are files can manage the filesystem.
        def prepare_namespace(_namespace)
        end

        def cleanup_namespace(_namespace)
        end

        # The statement which empties a table. SQLite has no TRUNCATE and uses
        # DELETE instead.
        def truncate_sql(qualified_table)
          "TRUNCATE #{qualified_table}"
        end

        #
        # Schema
        #

        # Translate a column definition written in the reference (MySQL) syntax
        # into this engine's syntax. MySQL returns it unchanged.
        def column_definition(definition)
          definition
        end

        # The statement(s) which create a table. Returns an array because some
        # engines express indexes as separate statements.
        def create_table_statements(namespace, table, options)
          raise NotImplementedError
        end

        # The statement which adds a column to an existing table.
        def add_column_sql(namespace, table, column, definition)
          raise NotImplementedError
        end

        # The statement which adds an index to an existing table.
        def add_index_sql(namespace, table, name, definition, unique: false)
          raise NotImplementedError
        end

        # The statement which changes the type of an existing column.
        def change_column_type_sql(namespace, table, column, definition)
          raise NotImplementedError
        end

        # Statements which convert a namespace to utf8mb4. Engines which are
        # UTF-8 already return an empty list.
        def convert_to_utf8mb4_statements(_namespace)
          []
        end

        # The statement which creates the namespace for a server.
        def create_namespace_sql(namespace)
          raise NotImplementedError
        end

        # The statement which removes the namespace for a server.
        def drop_namespace_sql(namespace)
          raise NotImplementedError
        end

        # The statement which returns a row when the namespace exists.
        def namespace_exists_sql(namespace)
          raise NotImplementedError
        end

        # The statement which lists the namespaces's tables matching a pattern.
        def list_tables_sql(namespace, like)
          raise NotImplementedError
        end

        # The table name held in a row returned by list_tables_sql.
        def table_name_from_row(row)
          raise NotImplementedError
        end

        # Extract column names from an index or primary-key fragment written in
        # the reference syntax, e.g. "`a`(8), `b`" => %w[a b].
        def index_columns(fragment)
          fragment.to_s.scan(/`([^`]+)`/).flatten
        end

      end
    end
  end
end
